/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import classes.Administrateur;
import dao.AdministrateurDAO;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import forms.PanelClient;

/**
 *
 * @author kabor
 */
public class FrameAcceuil extends javax.swing.JFrame {
        int count;
        int countSearch;
        int found;
        
    /**
     * Creates new form FrameAcceuil
     */
    public FrameAcceuil() {
        initComponents();
        combo_admin();
        date();
        time();
        this.setExtendedState(FrameAcceuil.MAXIMIZED_BOTH);
        jInternalFrame1.getContentPane().setBackground(Color.white);
        jInternalFrame1.getContentPane().setForeground(Color.white);
        jInternalFrame1.setBorder(null);
        
        if(Connect.profil.equals("Utilisateur")){
        gestion_caisse.setEnabled(false);
        gestion_caisse.setToolTipText("Accès internet! Vous devez être  admin");
        }
         
    }

   public void date() {
        Date d = new Date();
        SimpleDateFormat ladate = new SimpleDateFormat("dd-MM-yyyy");
        jdate.setText(ladate.format(d));

    }
     Timer t;
        SimpleDateFormat st;
   public void time() {
       
        t = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //throw new UnsupportedOperationException("Not supported yet.");
                Date dt = new Date();
                st = new SimpleDateFormat("hh:mm:ss a");
                jtime.setText(st.format(dt));
            }
        });
        t.start();
	}

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_searching = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btn_onOff = new javax.swing.JToggleButton();
        acceuil = new javax.swing.JButton();
        gestion_article = new javax.swing.JButton();
        gestion_service = new javax.swing.JButton();
        gestion_retrait = new javax.swing.JButton();
        gestion_depot = new javax.swing.JButton();
        gestion_caisse = new javax.swing.JButton();
        gestion_client = new javax.swing.JButton();
        gestion_users = new javax.swing.JButton();
        txt_nomsAffichage = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sidebar_acceuil = new javax.swing.JLabel();
        topbar_acceuil = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        btn_tpa = new javax.swing.JButton();
        btn_tps = new javax.swing.JButton();
        jtime = new javax.swing.JLabel();
        jdate = new javax.swing.JLabel();
        btn_choix = new javax.swing.JButton();
        btn_recu = new javax.swing.JButton();
        searchfield = new javax.swing.JTextField();
        searchBar = new javax.swing.JLabel();
        jLabel_fac = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel_etapes = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        fSbtn_admin = new LIB.FSButtonMD();
        fSGradientPanel1 = new LIB.FSGradientPanel();
        fSbtn_client = new LIB.FSButtonMD();
        fSbtn_abonne = new LIB.FSButtonMD();
        fSbtn_dep = new LIB.FSButtonMD();
        fSbtn_ram = new LIB.FSButtonMD();
        btn_log = new javax.swing.JButton();
        dateChooserPanel1 = new org.jfree.ui.DateChooserPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Press-In");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(900, 1080));
        setName("Acceuil"); // NOI18N
        setSize(new java.awt.Dimension(1500, 1500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1110, 719));
        jPanel1.setMinimumSize(new java.awt.Dimension(1110, 719));
        jPanel1.setPreferredSize(new java.awt.Dimension(1500, 1500));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_onOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/shutdown_24px_green.png"))); // NOI18N
        btn_onOff.setBorderPainted(false);
        btn_onOff.setContentAreaFilled(false);
        btn_onOff.setFocusPainted(false);
        btn_onOff.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/shutdown_24px_red.png"))); // NOI18N
        btn_onOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_onOffActionPerformed(evt);
            }
        });
        jPanel1.add(btn_onOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, -1, 50));

        acceuil.setFont(new java.awt.Font("Verdana Pro", 1, 12)); // NOI18N
        acceuil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/blog_40px.png"))); // NOI18N
        acceuil.setText("Acceuil");
        acceuil.setFocusPainted(false);
        acceuil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceuilActionPerformed(evt);
            }
        });
        jPanel1.add(acceuil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 170, 60));

        gestion_article.setFont(new java.awt.Font("Verdana Pro", 1, 12)); // NOI18N
        gestion_article.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Acceuil/drying_clothes_48px.png"))); // NOI18N
        gestion_article.setText("Articles");
        gestion_article.setFocusPainted(false);
        gestion_article.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestion_articleActionPerformed(evt);
            }
        });
        jPanel1.add(gestion_article, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 170, 60));

        gestion_service.setFont(new java.awt.Font("Verdana Pro", 1, 12)); // NOI18N
        gestion_service.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Acceuil/washing_machine_30px.png"))); // NOI18N
        gestion_service.setText("Services");
        gestion_service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestion_serviceActionPerformed(evt);
            }
        });
        jPanel1.add(gestion_service, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 170, 60));

        gestion_retrait.setFont(new java.awt.Font("Verdana Pro", 1, 12)); // NOI18N
        gestion_retrait.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Acceuil/caretaker_48px.png"))); // NOI18N
        gestion_retrait.setText("Ramassage");
        gestion_retrait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestion_retraitActionPerformed(evt);
            }
        });
        jPanel1.add(gestion_retrait, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 170, 60));

        gestion_depot.setFont(new java.awt.Font("Verdana Pro", 1, 12)); // NOI18N
        gestion_depot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Acceuil/delivery_30px.png"))); // NOI18N
        gestion_depot.setText("Livraison");
        gestion_depot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestion_depotActionPerformed(evt);
            }
        });
        jPanel1.add(gestion_depot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 170, 60));

        gestion_caisse.setFont(new java.awt.Font("Verdana Pro", 1, 12)); // NOI18N
        gestion_caisse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Acceuil/buy_48px.png"))); // NOI18N
        gestion_caisse.setText("Caisse");
        gestion_caisse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestion_caisseActionPerformed(evt);
            }
        });
        jPanel1.add(gestion_caisse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 170, 60));

        gestion_client.setFont(new java.awt.Font("Verdana Pro", 1, 12)); // NOI18N
        gestion_client.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Acceuil/people_working_together_48px.png"))); // NOI18N
        gestion_client.setText("Clients");
        gestion_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestion_clientActionPerformed(evt);
            }
        });
        jPanel1.add(gestion_client, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 170, 60));

        gestion_users.setFont(new java.awt.Font("Verdana Pro", 1, 12)); // NOI18N
        gestion_users.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Acceuil/name_tag_40px.png"))); // NOI18N
        gestion_users.setText("Personnel");
        gestion_users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestion_usersActionPerformed(evt);
            }
        });
        jPanel1.add(gestion_users, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 170, 60));

        txt_nomsAffichage.setBackground(new java.awt.Color(218, 218, 82));
        txt_nomsAffichage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomsAffichageActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nomsAffichage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, 110, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 153));
        jLabel3.setText("PRESS - IN");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Logo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 240, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/key_50px.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, 160, -1));

        sidebar_acceuil.setBackground(new java.awt.Color(218, 218, 82));
        sidebar_acceuil.setToolTipText("");
        sidebar_acceuil.setOpaque(true);
        jPanel1.add(sidebar_acceuil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 720));

        topbar_acceuil.setBackground(new java.awt.Color(218, 218, 82));
        topbar_acceuil.setOpaque(true);
        jPanel1.add(topbar_acceuil, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 1120, 50));

        jInternalFrame1.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrame1.setBorder(null);
        jInternalFrame1.setForeground(new java.awt.Color(255, 255, 255));
        jInternalFrame1.setFocusable(false);
        jInternalFrame1.setMaximumSize(new java.awt.Dimension(1110, 660));
        jInternalFrame1.setMinimumSize(new java.awt.Dimension(1110, 660));
        jInternalFrame1.setVisible(true);
        jInternalFrame1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jInternalFrame1MouseClicked(evt);
            }
        });
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_tpa.setFont(new java.awt.Font("Doulos SIL", 0, 14)); // NOI18N
        btn_tpa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Dashboard/article 48.png"))); // NOI18N
        btn_tpa.setText("Choisir Un Article");
        btn_tpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tpaActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(btn_tpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 330, 220, -1));

        btn_tps.setFont(new java.awt.Font("Doulos SIL", 0, 14)); // NOI18N
        btn_tps.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Dashboard/service 48.png"))); // NOI18N
        btn_tps.setText("Choisir Un Service");
        btn_tps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tpsActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(btn_tps, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, 220, -1));

        jtime.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        jtime.setForeground(new java.awt.Color(51, 255, 153));
        jtime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/btn/time_40px.png"))); // NOI18N
        jtime.setText("Time");
        jInternalFrame1.getContentPane().add(jtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 580, 170, 40));

        jdate.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        jdate.setForeground(new java.awt.Color(51, 255, 153));
        jdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/btn/Tear-Off Calendar_48px.png"))); // NOI18N
        jdate.setText("Date");
        jInternalFrame1.getContentPane().add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 580, 170, 40));

        btn_choix.setFont(new java.awt.Font("Doulos SIL", 0, 14)); // NOI18N
        btn_choix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Dashboard/icons8-choose-48.png"))); // NOI18N
        btn_choix.setText("S'abonner à un Service");
        btn_choix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_choixActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(btn_choix, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, 220, -1));

        btn_recu.setFont(new java.awt.Font("Doulos SIL", 0, 14)); // NOI18N
        btn_recu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Dashboard/icons8-get-a-receipt-48.png"))); // NOI18N
        btn_recu.setText("Prendre Un Reçu");
        btn_recu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_recuActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(btn_recu, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 490, 230, -1));

        searchfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchfield.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchfield.setEnabled(false);
        searchfield.setOpaque(false);
        searchfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchfieldMouseClicked(evt);
            }
        });
        searchfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchfieldKeyPressed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(searchfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, 130, 30));

        searchBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Dashboard/SearchBar0.png"))); // NOI18N
        searchBar.setName(""); // NOI18N
        searchBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBarMouseClicked(evt);
            }
        });
        jInternalFrame1.getContentPane().add(searchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 240, 70));

        jLabel_fac.setFont(new java.awt.Font("Perpetua", 3, 16)); // NOI18N
        jLabel_fac.setText("Vous voulez imprimer un facture?");
        jLabel_fac.setToolTipText("");
        jInternalFrame1.getContentPane().add(jLabel_fac, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 450, 220, 30));

        jButton1.setBackground(new java.awt.Color(51, 255, 153));
        jButton1.setFont(new java.awt.Font("Ravie", 0, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/btn/icons8-cash-counter-48.png"))); // NOI18N
        jButton1.setText("Caisse Journalier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 560, 230, 60));

        jLabel_etapes.setFont(new java.awt.Font("NSimSun", 1, 12)); // NOI18N
        jLabel_etapes.setText("<html>Suivez ces étapes pour aller plus vite à la livraison (si les services & articles sont déjà prédéfinis).");
        jInternalFrame1.getContentPane().add(jLabel_etapes, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 90, 240, 70));

        kGradientPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        kGradientPanel2.setkEndColor(new java.awt.Color(255, 204, 0));
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 260, 330));

        fSbtn_admin.setBackground(new java.awt.Color(0, 204, 153));
        fSbtn_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Acceuil/icons8-manager-64.png"))); // NOI18N
        fSbtn_admin.setText("Admins/Users");
        fSbtn_admin.setColorHover(new java.awt.Color(0, 204, 51));
        fSbtn_admin.setColorNormal(new java.awt.Color(0, 204, 153));
        fSbtn_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSbtn_adminActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(fSbtn_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 290, 80));

        fSGradientPanel1.setBorder(new org.jdesktop.swingx.border.IconBorder());
        fSGradientPanel1.setFSStartColor(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout fSGradientPanel1Layout = new javax.swing.GroupLayout(fSGradientPanel1);
        fSGradientPanel1.setLayout(fSGradientPanel1Layout);
        fSGradientPanel1Layout.setHorizontalGroup(
            fSGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
        );
        fSGradientPanel1Layout.setVerticalGroup(
            fSGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(fSGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 440, 250, 120));

        fSbtn_client.setBackground(new java.awt.Color(0, 204, 153));
        fSbtn_client.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Acceuil/client-64.png"))); // NOI18N
        fSbtn_client.setText("Clients Enregistrés");
        fSbtn_client.setColorHover(new java.awt.Color(0, 204, 51));
        fSbtn_client.setColorNormal(new java.awt.Color(0, 204, 153));
        fSbtn_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSbtn_clientActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(fSbtn_client, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 290, 80));

        fSbtn_abonne.setBackground(new java.awt.Color(0, 204, 153));
        fSbtn_abonne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Acceuil/icons8-client-64.png"))); // NOI18N
        fSbtn_abonne.setText("Clients Abonnés");
        fSbtn_abonne.setColorHover(new java.awt.Color(0, 204, 51));
        fSbtn_abonne.setColorNormal(new java.awt.Color(0, 204, 153));
        fSbtn_abonne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSbtn_abonneActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(fSbtn_abonne, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 290, 80));

        fSbtn_dep.setBackground(new java.awt.Color(0, 204, 153));
        fSbtn_dep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Acceuil/icons8-full-shopping-basket-64.png"))); // NOI18N
        fSbtn_dep.setText("Livraisons Actuelles");
        fSbtn_dep.setColorHover(new java.awt.Color(0, 204, 51));
        fSbtn_dep.setColorNormal(new java.awt.Color(0, 204, 153));
        fSbtn_dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSbtn_depActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(fSbtn_dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 290, 80));

        fSbtn_ram.setBackground(new java.awt.Color(0, 204, 153));
        fSbtn_ram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Acceuil/icons8-clear-shopping-cart-64.png"))); // NOI18N
        fSbtn_ram.setText("Retraits Actuelles");
        fSbtn_ram.setColorHover(new java.awt.Color(0, 204, 51));
        fSbtn_ram.setColorNormal(new java.awt.Color(0, 204, 153));
        fSbtn_ram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSbtn_ramActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(fSbtn_ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 290, 80));

        btn_log.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        btn_log.setForeground(new java.awt.Color(204, 204, 204));
        btn_log.setText("Connecté en tant que:");
        btn_log.setBorderPainted(false);
        btn_log.setContentAreaFilled(false);
        btn_log.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_log.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_log.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_logFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btn_logFocusLost(evt);
            }
        });
        jInternalFrame1.getContentPane().add(btn_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 30));
        jInternalFrame1.getContentPane().add(dateChooserPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        jPanel1.add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 1120, 660));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 735));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_onOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_onOffActionPerformed
        FrameAuthentification login = new FrameAuthentification();
        login.setVisible(true);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
        
        
    }//GEN-LAST:event_btn_onOffActionPerformed

    private void gestion_usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestion_usersActionPerformed
        jInternalFrame1.setContentPane(new PanelAdmin());
        this.setVisible(true);  
        jInternalFrame1.setBorder(null);
    }//GEN-LAST:event_gestion_usersActionPerformed

    private void gestion_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestion_clientActionPerformed
        jInternalFrame1.setContentPane(new PanelClient());
        this.setVisible(true);
        jInternalFrame1.setBorder(null);
    }//GEN-LAST:event_gestion_clientActionPerformed

    private void gestion_articleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestion_articleActionPerformed
        jInternalFrame1.setContentPane(new PanelArticle());
        this.setVisible(true);
        jInternalFrame1.setBorder(null);
    }//GEN-LAST:event_gestion_articleActionPerformed

    private void gestion_depotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestion_depotActionPerformed
        jInternalFrame1.setContentPane(new PanelDepot());
        this.setVisible(true);
        jInternalFrame1.setBorder(null);
    }//GEN-LAST:event_gestion_depotActionPerformed

    private void gestion_retraitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestion_retraitActionPerformed
        jInternalFrame1.setContentPane(new PanelRetrait());
        this.setVisible(true);
        jInternalFrame1.setBorder(null);
    }//GEN-LAST:event_gestion_retraitActionPerformed

    private void gestion_serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestion_serviceActionPerformed
        jInternalFrame1.setContentPane(new PanelService());
        this.setVisible(true);
        jInternalFrame1.setBorder(null);
    }//GEN-LAST:event_gestion_serviceActionPerformed

    private void gestion_caisseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestion_caisseActionPerformed
        jInternalFrame1.setContentPane(new PanelCaisse());
        this.setVisible(true);
        jInternalFrame1.setBorder(null);
        
        PanelCaisse pc = new PanelCaisse();
        // txt_nomsAffichage.addItem(administrateur.get(i).getPrenom()+"");
        //if (txt_nomsAffichage.equals(administrateur.get(i).getPrenom()+""))
        
    }//GEN-LAST:event_gestion_caisseActionPerformed

    private void acceuilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceuilActionPerformed
        //jInternalFrame1.setContentPane(new FrameAcceuil());
        //this.setVisible(true);
        //jInternalFrame1.getContentPane().setBackground(Color.white);
        //jInternalFrame1.getContentPane().setForeground(Color.white);
        
        FrameAcceuil connecting = new FrameAcceuil();
        connecting.setVisible(true);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
        
        //jInternalFrame1.setVisible(true);
        //jInternalFrame1.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        //jInternalFrame1.dispose();
        
        //FrameAcceuil jframe = new FrameAcceuil();
        //jframe.removeAll();
        //jframe.add(jInternalFrame1).setVisible(true);
        
        jInternalFrame1.setClosable(true);
        
    }//GEN-LAST:event_acceuilActionPerformed

    private void txt_nomsAffichageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomsAffichageActionPerformed
        /*if (txt_nomsAffichage.getSelectedItem().equals("Aurelie")) {
                gestion_caisse.setEnabled(true);
            }
        else {
            JOptionPane.showMessageDialog(null , "Vous devez etre admin");
            gestion_caisse.setEnabled(false);
        }*/
        
       /* AdministrateurDAO edao = new AdministrateurDAO();
        List<Administrateur> administrateur = edao.liste();
        
        for(int i = 0; i < administrateur.size(); i++) {
            //txt_nomsAffichage.addItem(administrateur.get(i).getPrenom()+"");
            //txt_nomsAffichage.equals(administrateur.get(i).getProfil_admin().getSelectedItem().toString());
            
            if ((administrateur.get(i).getProfil_admin().equals("Aurelie"))) {
                gestion_caisse.setEnabled(true);
            }
        else {
            //JOptionPane.showMessageDialog(null , "Vous devez etre admin");
            gestion_caisse.setEnabled(true);
        }
            //Profil_admin.equals("")
       }*/
    }//GEN-LAST:event_txt_nomsAffichageActionPerformed

    private void jInternalFrame1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInternalFrame1MouseClicked

        //jInternalFrame1.getContentPane().setBackground( Color.white );

        //JButton gestion_client1 = gestion_client;
        //PanelAdmin pa = new PanelAdmin();
        //jInternalFrame1.add(pa);
        //jInternalFrame1.setVisible(true);

        /*if (gestion_users.isSelected()) {
            jInternalFrame1.add(pa);
            jInternalFrame1.setVisible(true);

            //this.setContentPane(new PanelAdmin());
            //this.setVisible(true);
        }*/
    }//GEN-LAST:event_jInternalFrame1MouseClicked

    private void fSbtn_depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSbtn_depActionPerformed
        PanelDepot dep = new PanelDepot();
        fSbtn_dep.setText(dep.numdep.getText() + " Articles livrés");
    }//GEN-LAST:event_fSbtn_depActionPerformed

    private void fSbtn_abonneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSbtn_abonneActionPerformed
        PanelChoisir chx = new PanelChoisir();
        fSbtn_abonne.setText(chx.numchx.getText() + " Clients Abonnés");
    }//GEN-LAST:event_fSbtn_abonneActionPerformed

    private void fSbtn_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSbtn_clientActionPerformed
        PanelClient clt = new PanelClient();
        fSbtn_client.setText(clt.numclt.getText() + " Clients Enregistrés");
    }//GEN-LAST:event_fSbtn_clientActionPerformed

    private void fSbtn_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSbtn_adminActionPerformed
        PanelAdmin admin = new PanelAdmin();
        fSbtn_admin.setText(admin.numadmin.getText() + " Admins/Users Présents");
    }//GEN-LAST:event_fSbtn_adminActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PanelArticle pa = new PanelArticle();
        PanelService se = new PanelService();

        int v1, v2;
        v1 = Integer.valueOf(pa.sumArt.getText());
        v2 = Integer.valueOf(se.sumServ.getText());

        int s;
        s = v1+v2;

        DecimalFormat df = new DecimalFormat("#,###.00");
        jButton1.setText(""+df.format(s)+" CFA");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBarMouseClicked
        if(countSearch == 1) {
            searchfield.setEnabled(false);
            searchfield.setText("");

            countSearch = 0;
        }
    }//GEN-LAST:event_searchBarMouseClicked

    private void searchfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchfieldKeyPressed
        String getText = searchfield.getText();
        JDialog d = new JDialog();

        if (evt.getKeyCode()==KeyEvent.VK_ENTER && !searchfield.equals("")){

            if(getText.matches(".*ad.*")) {
                PanelAdmin pc = new PanelAdmin();
                d.add(pc);
                d.setSize(1000, 550);
                d.setVisible(true);
            }
            else if(getText.matches(".*uti.*")) {
                PanelAdmin pc = new PanelAdmin();
                d.add(pc);
                d.setSize(1000, 550);
                d.setVisible(true);
            }

            if(getText.matches(".*art.*")) {
                PanelArticle pa = new PanelArticle();
                d.add(pa);
                d.setSize(1100, 510);
                d.setVisible(true);
            }

            if(getText.matches(".*cai.*")) {
                PanelCaisse pc = new PanelCaisse();
                d.add(pc);
                d.setSize(1000, 500);
                d.setVisible(true);
            }

            if(getText.matches(".*cli.*")) {
                PanelClient pcl = new PanelClient();
                d.add(pcl);
                d.setSize(950, 630);
                d.setVisible(true);
            }

            if(getText.matches(".*dep.*")) {
                PanelDepot pd = new PanelDepot();
                d.add(pd);
                d.setSize(1200, 500);
                d.setVisible(true);
            }
            else if(getText.matches(".*liv.*")) {
                PanelDepot pd = new PanelDepot();
                d.add(pd);
                d.setSize(1200, 500);
                d.setVisible(true);
            }

            if(getText.matches(".*rec.*")) {
                PanelRecevoir pd = new PanelRecevoir();
                d.add(pd);
                d.setSize(1000, 500);
                d.setVisible(true);
            }
            else if(getText.matches(".*fac.*")) {
                PanelRecevoir pd = new PanelRecevoir();
                d.add(pd);
                d.setSize(1000, 500);
                d.setVisible(true);
            }

            if(getText.matches(".*retrai.*")) {
                PanelRetrait pd = new PanelRetrait();
                d.add(pd);
                d.setSize(1200, 500);
                d.setVisible(true);
            }
            else if(getText.matches(".*reti.*")) {
                PanelRetrait pd = new PanelRetrait();
                d.add(pd);
                d.setSize(1200, 500);
                d.setVisible(true);
            }
            else if(getText.matches(".*ram.*")) {
                PanelRetrait pd = new PanelRetrait();
                d.add(pd);
                d.setSize(1000, 500);
                d.setVisible(true);
            }

            if(getText.matches(".*ser.*")) {
                PanelService pc = new PanelService();
                d.add(pc);
                d.setSize(1000, 500);
                d.setVisible(true);
            }

            if (getText.isEmpty()) {
                JOptionPane.showMessageDialog(null , "Veuillez saisir!");
            }

            /*if (getText.isEmpty()) {
                JOptionPane.showMessageDialog(null , "Cette recherche n'existe pas! Veuillez réessayer.");
            }*/

        }
        /*else {
            JOptionPane.showMessageDialog(null , "Cette recherche n'existe pas! Veuillez réessayer.");
        }*/
    }//GEN-LAST:event_searchfieldKeyPressed

    private void searchfieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchfieldMouseClicked

        if(countSearch == 0) {
            searchfield.setEnabled(true);
            searchfield.setText("search");

            if(searchfield.isFocusable()){
                //searchfield.setBorder(new LineBorder(Color.blue,0));
            }

            countSearch = 1;
        }
        else{
            JOptionPane.showMessageDialog(null , "Cette recherche n'existe pas! Veuillez réessayer.");
        }

        // D:\TECHNO-LAB\Programmation Java-JEE\NetBeans\GestionDePressing\src\icones\Dashboard
        //String callimage = "GestionDePressing/Resources/Images/SearchBarFocusGlow.png";
        //ImageIcon focus = new ImageIcon(getClass().getResource(callimage));
        //ImageIcon focus = new ImageIcon(getClass().getResource("/SearchBarFocusGlow.png"));
        //jToggleButton1.setIcon(focus);
    }//GEN-LAST:event_searchfieldMouseClicked

    private void btn_recuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_recuActionPerformed
        JDialog d = new JDialog();
        PanelRecevoir recu = new PanelRecevoir();
        d.add(recu);
        d.setSize(1000, 500);
        d.setLocation(200, 100);
        d.setVisible(true);
    }//GEN-LAST:event_btn_recuActionPerformed

    private void btn_choixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_choixActionPerformed
        JDialog d = new JDialog();
        PanelChoisir choix = new PanelChoisir();
        d.add(choix);
        d.setSize(1000, 500);
        d.setLocation(200, 100);
        d.setVisible(true);
    }//GEN-LAST:event_btn_choixActionPerformed

    private void btn_tpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tpsActionPerformed
        //jInternalFrame1.setContentPane(new PanelTypeService());
        //this.setVisible(true);
        //jInternalFrame1.setBorder(null);

        JDialog d = new JDialog();
        PanelTypeService tps = new PanelTypeService();
        d.add(tps);
        d.setSize(1000, 500);
        d.setLocation(200, 100);
        d.setVisible(true);
    }//GEN-LAST:event_btn_tpsActionPerformed

    private void btn_tpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tpaActionPerformed
        //jInternalFrame1.setContentPane(new PanelTypeArticle());
        //this.setVisible(true);
        //jInternalFrame1.setBorder(null);

        JDialog d = new JDialog();
        PanelTypeArticle tpa = new PanelTypeArticle();
        d.add(tpa);
        d.setSize(1000, 500);
        d.setLocation(200, 100);
        d.setVisible(true);
    }//GEN-LAST:event_btn_tpaActionPerformed

    private void fSbtn_ramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSbtn_ramActionPerformed
        PanelRetrait ram = new PanelRetrait();
        fSbtn_ram.setText(ram.numram.getText() + " Articles retirés");
    }//GEN-LAST:event_fSbtn_ramActionPerformed

    private void btn_logFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_logFocusGained
        Connect ct = new Connect();
        btn_log.setText("Connecté en tant que: " + ct.profil);
    }//GEN-LAST:event_btn_logFocusGained

    private void btn_logFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_logFocusLost
        //Connect ct = new Connect();
        //btn_log.setText("Connecté en tant que: " + ct.profil);
    }//GEN-LAST:event_btn_logFocusLost

    private void combo_admin() {
       /* AdministrateurDAO edao = new AdministrateurDAO();
        List<Administrateur> administrateur = edao.liste();
        //txt_nomsAffichage.addItem("");
        
        for(int i = 0; i < administrateur.size(); i++) {
            txt_nomsAffichage.addItem(administrateur.get(i).getPrenom()+"");
            
            /*if (txt_nomsAffichage.getSelectedItem().equals("Aurelie")) {
                gestion_caisse.setEnabled(true);
            }
        
            //Profil_admin.equals("")
       }*/
       txt_nomsAffichage.addItem(Connect.prenom);
       
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAcceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAcceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAcceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAcceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAcceuil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceuil;
    private javax.swing.JButton btn_choix;
    private javax.swing.JButton btn_log;
    private javax.swing.JToggleButton btn_onOff;
    private javax.swing.JButton btn_recu;
    private javax.swing.JButton btn_tpa;
    private javax.swing.JButton btn_tps;
    private javax.swing.ButtonGroup buttonGroup_searching;
    private org.jfree.ui.DateChooserPanel dateChooserPanel1;
    private LIB.FSGradientPanel fSGradientPanel1;
    private LIB.FSButtonMD fSbtn_abonne;
    private LIB.FSButtonMD fSbtn_admin;
    private LIB.FSButtonMD fSbtn_client;
    private LIB.FSButtonMD fSbtn_dep;
    private LIB.FSButtonMD fSbtn_ram;
    private javax.swing.JButton gestion_article;
    private javax.swing.JButton gestion_caisse;
    private javax.swing.JButton gestion_client;
    private javax.swing.JButton gestion_depot;
    private javax.swing.JButton gestion_retrait;
    private javax.swing.JButton gestion_service;
    private javax.swing.JButton gestion_users;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_etapes;
    private javax.swing.JLabel jLabel_fac;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jdate;
    private javax.swing.JLabel jtime;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel searchBar;
    private javax.swing.JTextField searchfield;
    private javax.swing.JLabel sidebar_acceuil;
    private javax.swing.JLabel topbar_acceuil;
    private javax.swing.JComboBox<String> txt_nomsAffichage;
    // End of variables declaration//GEN-END:variables
}
