/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import dao.AdministrateurDAO;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author kabor
 */
public class FrameAuthentification extends javax.swing.JFrame {

    /**
     * Creates new form FrameAuthentification
     */
    public FrameAuthentification() {
        initComponents();
        this.setExtendedState(FrameAcceuil.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        choixLabel = new javax.swing.JLabel();
        adminLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        adminBtn1 = new javax.swing.JToggleButton();
        userBtn1 = new javax.swing.JToggleButton();
        yellowBg = new javax.swing.JLabel();
        profile_titre = new javax.swing.JLabel();
        btn_connection = new javax.swing.JButton();
        loginPanel = new javax.swing.JLabel();
        titreConnex = new javax.swing.JLabel();
        txt_nom = new javax.swing.JTextField();
        txt_prenom = new javax.swing.JTextField();
        txt_login = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 218, 82), 10));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        choixLabel.setFont(new java.awt.Font("Painter PERSONAL USE ONLY", 0, 24)); // NOI18N
        choixLabel.setForeground(new java.awt.Color(30, 93, 190));
        choixLabel.setText("En tant que");
        jPanel1.add(choixLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 130, 60));

        adminLabel.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        adminLabel.setForeground(new java.awt.Color(255, 255, 255));
        adminLabel.setText("ADMIN");
        jPanel1.add(adminLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 110, 40));

        userLabel.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        userLabel.setForeground(new java.awt.Color(255, 255, 255));
        userLabel.setText("USER");
        jPanel1.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 70, 40));

        adminBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/adminBtn_white.png"))); // NOI18N
        adminBtn1.setBorder(null);
        adminBtn1.setBorderPainted(false);
        adminBtn1.setContentAreaFilled(false);
        adminBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminBtn1.setFocusPainted(false);
        adminBtn1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/adminBtn_green.png"))); // NOI18N
        adminBtn1.setRolloverEnabled(false);
        adminBtn1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/adminBtn_green.png"))); // NOI18N
        adminBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(adminBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        userBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/userBtn_white.png"))); // NOI18N
        userBtn1.setBorder(null);
        userBtn1.setBorderPainted(false);
        userBtn1.setContentAreaFilled(false);
        userBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userBtn1.setFocusPainted(false);
        userBtn1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/userBtn_green.png"))); // NOI18N
        userBtn1.setRolloverEnabled(false);
        userBtn1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/userBtn_green.png"))); // NOI18N
        userBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(userBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));

        yellowBg.setBackground(new java.awt.Color(255, 255, 255));
        yellowBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/yellowBg.jpg"))); // NOI18N
        jPanel1.add(yellowBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 791, 700));

        profile_titre.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        profile_titre.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(profile_titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 230, -1, -1));

        btn_connection.setBackground(new java.awt.Color(51, 153, 255));
        btn_connection.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_connection.setForeground(new java.awt.Color(255, 255, 255));
        btn_connection.setText("Connection");
        btn_connection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_connectionActionPerformed(evt);
            }
        });
        jPanel1.add(btn_connection, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 590, -1, -1));

        loginPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/loginPanel3.png"))); // NOI18N
        jPanel1.add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 110, -1, -1));

        titreConnex.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        titreConnex.setForeground(new java.awt.Color(255, 240, 194));
        titreConnex.setText("Connectez - Vous");
        jPanel1.add(titreConnex, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, 380, 50));

        txt_nom.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        txt_nom.setForeground(new java.awt.Color(51, 153, 255));
        txt_nom.setText("Nom");
        txt_nom.setBorder(null);
        txt_nom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nomFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nomFocusLost(evt);
            }
        });
        jPanel1.add(txt_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 260, 300, 60));

        txt_prenom.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        txt_prenom.setForeground(new java.awt.Color(51, 153, 255));
        txt_prenom.setText("Prenom");
        txt_prenom.setBorder(null);
        txt_prenom.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_prenom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_prenomFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_prenomFocusLost(evt);
            }
        });
        jPanel1.add(txt_prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 350, 300, 50));

        txt_login.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        txt_login.setForeground(new java.awt.Color(51, 153, 255));
        txt_login.setText("Login");
        txt_login.setBorder(null);
        txt_login.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_loginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_loginFocusLost(evt);
            }
        });
        jPanel1.add(txt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 430, 300, 50));

        txt_password.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        txt_password.setForeground(new java.awt.Color(51, 153, 255));
        txt_password.setText("Password");
        txt_password.setBorder(null);
        txt_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_passwordFocusLost(evt);
            }
        });
        jPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 510, 300, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nomFocusGained
        if(txt_nom.getText().equals("Nom")) {
            txt_nom.setText("");
            txt_nom.requestFocus();
            txt_nom.setForeground(new Color(51,153,255));
        }
    }//GEN-LAST:event_txt_nomFocusGained

    private void txt_nomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nomFocusLost
        if(txt_nom.getText().equals("")) {
            txt_nom.setText("Nom");
            txt_nom.setForeground(new Color(51,153,255));
        }
    }//GEN-LAST:event_txt_nomFocusLost

    private void txt_prenomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_prenomFocusGained
        if(txt_prenom.getText().equals("Prenom")) {
            txt_prenom.setText("");
            txt_prenom.requestFocus();
            txt_prenom.setForeground(new Color(51,153,255));
        }
    }//GEN-LAST:event_txt_prenomFocusGained

    private void txt_prenomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_prenomFocusLost
        if(txt_prenom.getText().equals("")) {
            txt_prenom.setText("Prenom");
            txt_prenom.setForeground(new Color(51,153,255));
        }
    }//GEN-LAST:event_txt_prenomFocusLost

    private void txt_loginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_loginFocusGained
        if(txt_login.getText().equals("Login")) {
            txt_login.setText("");
            txt_login.requestFocus();
            txt_login.setForeground(new Color(51,153,255));
        }
    }//GEN-LAST:event_txt_loginFocusGained

    private void txt_loginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_loginFocusLost
        if(txt_login.getText().equals("")) {
            txt_login.setText("Login");
            txt_login.setForeground(new Color(51,153,255));
        }
    }//GEN-LAST:event_txt_loginFocusLost

    private void txt_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordFocusGained

        /*if(saisirPassword.getPassword().equals("Password")) {
            saisirPassword.setText("");
            saisirPassword.setForeground(new Color(51,153,255));
        }*/
        if(txt_password.getText().equals("Password")) {
            txt_password.setText("");
            txt_password.requestFocus();
            txt_password.setForeground(new Color(51,153,255));
            //String Password_admin = String.valueOf(saisirPassword.getPassword());
        }
        
    }//GEN-LAST:event_txt_passwordFocusGained

    private void txt_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordFocusLost

        /*if(saisirPassword.getPassword().equals("")) {
            saisirPassword.setText("Password");
            saisirPassword.setForeground(new Color(51,153,255));
        }*/
        if(txt_password.getText().length()==0) {
            txt_password.setText("Password");
            txt_password.setForeground(new Color(51,153,255));
        }
    }//GEN-LAST:event_txt_passwordFocusLost

    private void adminBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBtn1ActionPerformed
        if(adminBtn1.isSelected()) {
            userBtn1.setSelected(false);
            profile_titre.setText("Profile Aministratif");
        } else if(userBtn1.isSelected()) {
            adminBtn1.setSelected(false);
            profile_titre.setText("Profile Utilisateur");
        }
    }//GEN-LAST:event_adminBtn1ActionPerformed

    private void userBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBtn1ActionPerformed
        if(userBtn1.isSelected()) {
            adminBtn1.setSelected(false);
            profile_titre.setText("Profile Utilisateur");
        } else if(adminBtn1.isSelected()) {
            userBtn1.setSelected(false);
            profile_titre.setText("Profile Administrateur");
        }
    }//GEN-LAST:event_userBtn1ActionPerformed

    private void btn_connectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_connectionActionPerformed
        /*FrameAcceuil connecting = new FrameAcceuil();
        connecting.setVisible(true);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();*/
       
        
        AdministrateurDAO edao = new AdministrateurDAO();
        
        String Login_admin = txt_login.getText();
        String Password_admin = String.valueOf(txt_password.getPassword());
        
        if (Login_admin.equals("") || Password_admin.equals("")) {
            JOptionPane.showMessageDialog(this, "Veillez renseigner tous les champs!");
        } else {
            boolean v = edao.connexion(Login_admin, Password_admin);
            if(v==true) {
                List<String> tb  = edao.getProfil(Login_admin, Password_admin);
                Connect.profil=tb.get(0);
                Connect.prenom=tb.get(1);
                this.dispose();
                FrameAcceuil fa = new FrameAcceuil();
                fa.setVisible(true);
            } else 
               JOptionPane.showMessageDialog(this, "login ou password incorrect!"); 
        }
 
        
    }//GEN-LAST:event_btn_connectionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAuthentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAuthentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAuthentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAuthentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAuthentification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton adminBtn1;
    private javax.swing.JLabel adminLabel;
    private javax.swing.JButton btn_connection;
    private javax.swing.JLabel choixLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginPanel;
    private javax.swing.JLabel profile_titre;
    private javax.swing.JLabel titreConnex;
    private javax.swing.JTextField txt_login;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_prenom;
    private javax.swing.JToggleButton userBtn1;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel yellowBg;
    // End of variables declaration//GEN-END:variables
}
