/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import classes.Service;
import dao.ServiceDAO;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import report.ReportService;

/**
 *
 * @author kabor
 */
public class PanelService extends javax.swing.JPanel {

    /**
     * Creates new form PanelService
     */
    public PanelService() {
        initComponents();
        liste_service();
        sumServ.setText(Integer.toString(calculService()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_prixus = new javax.swing.JFormattedTextField();
        btn_enregistrer = new javax.swing.JButton();
        btn_supprimer = new javax.swing.JButton();
        btn_modifier = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_nums = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_service = new javax.swing.JTable();
        txt_libelles = new javax.swing.JComboBox<>();
        btn_lavage = new javax.swing.JToggleButton();
        btn_nettoyage = new javax.swing.JToggleButton();
        btn_repassage = new javax.swing.JToggleButton();
        btn_teinture = new javax.swing.JToggleButton();
        btn_sechage = new javax.swing.JToggleButton();
        sumServ = new javax.swing.JLabel();
        btn_imprimer = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_rechercher = new javax.swing.JTextField();
        loup = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion Des Services", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Teko", 1, 36))); // NOI18N

        jLabel1.setText("Libelle");

        jLabel2.setText("Prix Unitaire");

        btn_enregistrer.setFont(new java.awt.Font("Painting With Chocolate", 0, 11)); // NOI18N
        btn_enregistrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/btn/save_50px.png"))); // NOI18N
        btn_enregistrer.setText("Enregistrer");
        btn_enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enregistrerActionPerformed(evt);
            }
        });

        btn_supprimer.setFont(new java.awt.Font("Painting With Chocolate", 0, 11)); // NOI18N
        btn_supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/btn/Delete_48px.png"))); // NOI18N
        btn_supprimer.setText("Supprimer");
        btn_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimerActionPerformed(evt);
            }
        });

        btn_modifier.setFont(new java.awt.Font("Painting With Chocolate", 0, 11)); // NOI18N
        btn_modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/btn/icons8-modify-48.png"))); // NOI18N
        btn_modifier.setText("Modifier");
        btn_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifierActionPerformed(evt);
            }
        });

        jLabel3.setText("Numero");

        tb_service.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDS", "Libelle Service", "Numero Service", "Prix Unitaire Service"
            }
        ));
        tb_service.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_serviceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_service);

        buttonGroup1.add(btn_lavage);
        btn_lavage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/FrameService/icons8-washing-machine-50.png"))); // NOI18N
        btn_lavage.setBorderPainted(false);
        btn_lavage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lavageActionPerformed(evt);
            }
        });

        buttonGroup1.add(btn_nettoyage);
        btn_nettoyage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/FrameService/icons8-softener-50.png"))); // NOI18N
        btn_nettoyage.setBorderPainted(false);
        btn_nettoyage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nettoyageActionPerformed(evt);
            }
        });

        buttonGroup1.add(btn_repassage);
        btn_repassage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/FrameService/ironing-50 (2).png"))); // NOI18N
        btn_repassage.setBorderPainted(false);
        btn_repassage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_repassageActionPerformed(evt);
            }
        });

        buttonGroup1.add(btn_teinture);
        btn_teinture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/FrameService/icons8-color-palette-50.png"))); // NOI18N
        btn_teinture.setBorderPainted(false);
        btn_teinture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_teintureActionPerformed(evt);
            }
        });

        buttonGroup1.add(btn_sechage);
        btn_sechage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/FrameService/icons8-cleaning-50.png"))); // NOI18N
        btn_sechage.setToolTipText("");
        btn_sechage.setBorderPainted(false);
        btn_sechage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sechageActionPerformed(evt);
            }
        });

        sumServ.setForeground(new java.awt.Color(255, 255, 255));

        btn_imprimer.setFont(new java.awt.Font("Painting With Chocolate", 0, 11)); // NOI18N
        btn_imprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/btn/icons8-print-48.png"))); // NOI18N
        btn_imprimer.setText("Imprimer");
        btn_imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimerActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel4.setText("LAVAGE");

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel5.setText("NETTOYAGE");

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel6.setText("REPASSAGE");

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel7.setText("TEINTURE");

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel8.setText("SECHAGE");

        txt_rechercher.setFont(new java.awt.Font("Rockwell Condensed", 0, 14)); // NOI18N
        txt_rechercher.setForeground(new java.awt.Color(153, 153, 153));
        txt_rechercher.setText("Entrez Votre Recherche...");
        txt_rechercher.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_rechercherFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_rechercherFocusLost(evt);
            }
        });
        txt_rechercher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_rechercherKeyReleased(evt);
            }
        });

        loup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Dashboard/searchloup1.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_lavage)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_nettoyage)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_repassage)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_teinture)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_sechage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(loup))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_enregistrer)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_modifier)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_supprimer))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(txt_nums, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(68, 68, 68)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_prixus))
                                        .addComponent(txt_libelles, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(sumServ, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_imprimer))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_lavage)
                    .addComponent(btn_nettoyage)
                    .addComponent(btn_repassage)
                    .addComponent(btn_teinture)
                    .addComponent(btn_sechage)
                    .addComponent(loup)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txt_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txt_libelles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txt_nums, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txt_prixus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(sumServ, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(btn_imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enregistrerActionPerformed
        ServiceDAO edao = new ServiceDAO();

        String LibelleS = txt_libelles.getSelectedItem().toString();
        String NumS = txt_nums.getText();
        String PrixUS = txt_prixus.getText();

        if (LibelleS.equals("") || NumS.equals("") || PrixUS.equals("")) {
            JOptionPane.showMessageDialog(this, "Veillez renseigner tous les champs!");
        } else {
            Service ser = new Service(LibelleS, Integer.parseInt(NumS), Integer.parseInt(PrixUS));
            edao.inserer(ser);
            vider();
            liste_service();
        }
    }//GEN-LAST:event_btn_enregistrerActionPerformed

    private void btn_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimerActionPerformed
        int index = tb_service.getSelectedRow();

        if(index==-1) {
            JOptionPane.showMessageDialog(this, "Veillez selectionner une ligne!");
        } else {
            int id = (int) tb_service.getValueAt(index, 0);
            ServiceDAO edao = new ServiceDAO();
            edao.supprimer(id);
            vider();
            liste_service();
        }
    }//GEN-LAST:event_btn_supprimerActionPerformed

    private void btn_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifierActionPerformed
        ServiceDAO edao = new ServiceDAO();

        String LibelleS = txt_libelles.getSelectedItem().toString();
        String NumS = txt_nums.getText();
        String PrixUS = txt_prixus.getText();

        if (LibelleS.equals("") || NumS.equals("") || PrixUS.equals("")) {
            JOptionPane.showMessageDialog(this, "Veillez renseigner tous les champs!");
        } else {
            int index = tb_service.getSelectedRow();
            int id = (int) tb_service.getValueAt(index, 0);
            Service ser = new Service(LibelleS, Integer.parseInt(NumS), Integer.parseInt(PrixUS));
            edao.modifier(ser, id);
            vider();
            liste_service();
        }
    }//GEN-LAST:event_btn_modifierActionPerformed

    private void tb_serviceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_serviceMouseClicked
        int index = tb_service.getSelectedRow();

        if(index!=-1) {
            int id = (int) tb_service.getValueAt(index, 0);
            ServiceDAO edao = new ServiceDAO();
            Service serl = edao.rechercher(id);

            txt_libelles.setSelectedItem(serl.getLibelleS());
            txt_nums.setText(serl.getNumS()+"");
            txt_prixus.setText(serl.getPrixUS()+"");
        }
    }//GEN-LAST:event_tb_serviceMouseClicked

    private void btn_lavageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lavageActionPerformed
        if(btn_lavage.isSelected() == true) {
          btn_lavage.setBackground(Color.yellow); 
          //btn_lavage.setBackground(new Color (255,255,204,255));
          
          txt_libelles.removeAllItems();
          txt_libelles.addItem("Synthétique");
          txt_libelles.addItem("Coton");
          txt_libelles.addItem("Délicat");
          txt_libelles.addItem("Mixte");
          txt_libelles.addItem("Laine");
          txt_libelles.addItem("BabyCare");
          txt_libelles.addItem("Essorage");
          
          btn_nettoyage.setBackground(Color.white);
          btn_repassage.setBackground(Color.white);
          btn_teinture.setBackground(Color.white);
          btn_sechage.setBackground(Color.white);
        
        } else if (btn_lavage.isSelected() == false) {
            btn_lavage.setBackground(Color.white);
            txt_libelles.removeAllItems();
        }
    }//GEN-LAST:event_btn_lavageActionPerformed

    private void btn_nettoyageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nettoyageActionPerformed
        if(btn_nettoyage.isSelected() == true) {
          btn_nettoyage.setBackground(Color.yellow); 
          //btn_nettoyage.setBackground(new Color (255,255,204,255));
          
          txt_libelles.removeAllItems();
          txt_libelles.addItem("Nettoyage Chimique");
          txt_libelles.addItem("Nettoyage modéré");
          txt_libelles.addItem("Nettoyage à sec");
          txt_libelles.addItem("Nettoyage à l'eau");
          txt_libelles.addItem("Ne pas nettoyer");
          
          btn_lavage.setBackground(Color.white);
          btn_repassage.setBackground(Color.white);
          btn_teinture.setBackground(Color.white);
          btn_sechage.setBackground(Color.white);
        
        } else if (btn_nettoyage.isSelected() == false) {
            btn_nettoyage.setBackground(Color.white);
            txt_libelles.removeAllItems();
        }
    }//GEN-LAST:event_btn_nettoyageActionPerformed

    private void btn_repassageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_repassageActionPerformed
        if(btn_repassage.isSelected() == true) {
          btn_repassage.setBackground(Color.yellow); 
          //btn_repassage.setBackground(new Color (255,255,204,255));
          
          txt_libelles.removeAllItems();
          txt_libelles.addItem("Repassage à température modérée");
          txt_libelles.addItem("Repassage à température faible");
          txt_libelles.addItem("Repassage à fer chaud");
          txt_libelles.addItem("Ne pas repasser");
          
          btn_lavage.setBackground(Color.white);
          btn_nettoyage.setBackground(Color.white);
          btn_teinture.setBackground(Color.white);
          btn_sechage.setBackground(Color.white);
        
        } else if (btn_repassage.isSelected() == false) {
            btn_repassage.setBackground(Color.white);
            txt_libelles.removeAllItems();
        }
    }//GEN-LAST:event_btn_repassageActionPerformed

    private void btn_teintureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_teintureActionPerformed
        if(btn_teinture.isSelected() == true) {
          btn_teinture.setBackground(Color.yellow); 
          //btn_teinture.setBackground(new Color (255,255,204,255));
          
          txt_libelles.removeAllItems();
          txt_libelles.addItem("Tous types de blanchiments");
          txt_libelles.addItem("Blanchiment uniquement avec produits oxygénés");
          txt_libelles.addItem("Blanchiment interdit");
          txt_libelles.addItem("Coloria - Teintures textiles");
          txt_libelles.addItem("IDEAL - Teintures textiles");
          txt_libelles.addItem("Rubigine - Détachants Extrême");
          txt_libelles.addItem("Teinture interdit");
          
          btn_lavage.setBackground(Color.white);
          btn_repassage.setBackground(Color.white);
          btn_nettoyage.setBackground(Color.white);
          btn_sechage.setBackground(Color.white);
        
        } else if (btn_teinture.isSelected() == false) {
            btn_teinture.setBackground(Color.white);
            txt_libelles.removeAllItems();
        }
    }//GEN-LAST:event_btn_teintureActionPerformed

    private void btn_sechageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sechageActionPerformed
        if(btn_sechage.isSelected() == true) {
          btn_sechage.setBackground(Color.yellow); 
          //btn_sechage.setBackground(new Color (255,255,204,255));
          
          txt_libelles.removeAllItems();
          txt_libelles.addItem("Séchage normal");
          txt_libelles.addItem("Séchage à base température");
          txt_libelles.addItem("Séchage à température élevé");
          txt_libelles.addItem("Séchage interdit");
          
          btn_lavage.setBackground(Color.white);
          btn_repassage.setBackground(Color.white);
          btn_teinture.setBackground(Color.white);
          btn_nettoyage.setBackground(Color.white);
        
        } else if (btn_sechage.isSelected() == false) {
            btn_sechage.setBackground(Color.white);
            txt_libelles.removeAllItems();
        }
    }//GEN-LAST:event_btn_sechageActionPerformed

    private void btn_imprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimerActionPerformed
        ReportService re = new ReportService();
        re.afficher_report();
    }//GEN-LAST:event_btn_imprimerActionPerformed

    private void txt_rechercherFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_rechercherFocusGained
        if(txt_rechercher.getText().equals("Entrez Votre Recherche...")){
            txt_rechercher.setText("");
            txt_rechercher.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_rechercherFocusGained

    private void txt_rechercherFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_rechercherFocusLost
        if(txt_rechercher.getText().equals("")){
            txt_rechercher.setText("Entrez Votre Recherche...");
            txt_rechercher.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_rechercherFocusLost

    private void txt_rechercherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rechercherKeyReleased
        DefaultTableModel model = (DefaultTableModel) tb_service.getModel();
        TableRowSorter sorter = new TableRowSorter(model);
        tb_service.setRowSorter(sorter);
        String rech = txt_rechercher.getText();
        sorter.setRowFilter(RowFilter.regexFilter(rech));

    }//GEN-LAST:event_txt_rechercherKeyReleased


    private void liste_service() {
        ServiceDAO edao = new ServiceDAO();
        List<Service> service = edao.liste();
        
        for(int i = 0; i < service.size(); i++) {
            ((DefaultTableModel) tb_service.getModel()).addRow(new Object[] {
            service.get(i).getIDS(),
            service.get(i).getLibelleS(),
            service.get(i).getNumS(),
            service.get(i).getPrixUS(),
        });
       }
    }

   public void vider() {
        txt_libelles.setSelectedItem("");
        txt_nums.setText("");
        txt_prixus.setText("");
        
        DefaultTableModel model = (DefaultTableModel) tb_service.getModel();
        int n = model.getRowCount();
        for(int i = n - 1; i >= 0; --i) {
            model.removeRow(i);
        }
    }
    
    public int calculService() {
     
        int rowsCount = tb_service.getRowCount();
        
        int total = 0; 
        for(int i = 0; i < rowsCount; i++){
            total = total+Integer.parseInt(tb_service.getValueAt(i, 3).toString());
        } 
        return total;
        //sum.setText(Integer.toString(calculer()));
     }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_enregistrer;
    private javax.swing.JButton btn_imprimer;
    private javax.swing.JToggleButton btn_lavage;
    private javax.swing.JButton btn_modifier;
    private javax.swing.JToggleButton btn_nettoyage;
    private javax.swing.JToggleButton btn_repassage;
    private javax.swing.JToggleButton btn_sechage;
    private javax.swing.JButton btn_supprimer;
    private javax.swing.JToggleButton btn_teinture;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loup;
    public static javax.swing.JLabel sumServ;
    private javax.swing.JTable tb_service;
    private javax.swing.JComboBox<String> txt_libelles;
    private javax.swing.JTextField txt_nums;
    private javax.swing.JFormattedTextField txt_prixus;
    private javax.swing.JTextField txt_rechercher;
    // End of variables declaration//GEN-END:variables
}
