/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import classes.Administrateur;
import classes.Client;
import classes.Recevoir;
import dao.AdministrateurDAO;
import dao.ClientDAO;
import dao.RecevoirDAO;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import report.ReportRecevoir;

/**
 *
 * @author kabor
 */
public class PanelRecevoir extends javax.swing.JPanel {

    /**
     * Creates new form PanelChoisir
     */
    public PanelRecevoir() {
        initComponents();
        combo_admin();
        combo_client();
        liste_recu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_admin = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txt_client = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btn_enregistrer = new javax.swing.JButton();
        btn_supprimer = new javax.swing.JButton();
        btn_modifier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_recu = new javax.swing.JTable();
        btn_imprimer = new javax.swing.JButton();
        txt_rechercher = new javax.swing.JTextField();
        loup = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Les Reçus", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Teko", 1, 36))); // NOI18N

        jLabel2.setText("Admin");

        jLabel3.setText("Client");

        btn_enregistrer.setFont(new java.awt.Font("Painting With Chocolate", 0, 11)); // NOI18N
        btn_enregistrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/btn/save_50px.png"))); // NOI18N
        btn_enregistrer.setText("Enregistrer");
        btn_enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enregistrerActionPerformed(evt);
            }
        });

        btn_supprimer.setFont(new java.awt.Font("Painting With Chocolate", 0, 11)); // NOI18N
        btn_supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/btn/Delete_48px.png"))); // NOI18N
        btn_supprimer.setText("Supprimer");
        btn_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimerActionPerformed(evt);
            }
        });

        btn_modifier.setFont(new java.awt.Font("Painting With Chocolate", 0, 11)); // NOI18N
        btn_modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/btn/icons8-modify-48.png"))); // NOI18N
        btn_modifier.setText("Modifier");
        btn_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifierActionPerformed(evt);
            }
        });

        tb_recu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_recevoir", "Nom Admin", "Prenom du Client"
            }
        ));
        tb_recu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_recuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_recu);

        btn_imprimer.setFont(new java.awt.Font("Painting With Chocolate", 0, 11)); // NOI18N
        btn_imprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/btn/icons8-print-48.png"))); // NOI18N
        btn_imprimer.setText("Imprimer");
        btn_imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimerActionPerformed(evt);
            }
        });

        txt_rechercher.setFont(new java.awt.Font("Rockwell Condensed", 0, 14)); // NOI18N
        txt_rechercher.setForeground(new java.awt.Color(153, 153, 153));
        txt_rechercher.setText("Entrez Votre Recherche...");
        txt_rechercher.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_rechercherFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_rechercherFocusLost(evt);
            }
        });
        txt_rechercher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_rechercherKeyReleased(evt);
            }
        });

        loup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Dashboard/searchloup1.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_client, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_imprimer)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_enregistrer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_modifier)
                        .addGap(18, 18, 18)
                        .addComponent(btn_supprimer)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txt_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(loup))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(loup)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txt_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                        .addComponent(btn_imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enregistrerActionPerformed
        RecevoirDAO edao = new RecevoirDAO();
        ClientDAO cdao = new ClientDAO();
        AdministrateurDAO adao = new AdministrateurDAO();

        //String ID_Admin = txt_admin.getSelectedItem().toString();
        String Nom = txt_admin.getSelectedItem().toString();
        
        //String ID_Client = txt_client.getSelectedItem().toString();
        String Prenom = txt_client.getSelectedItem().toString();

        if (Nom.equals("") || Prenom.equals("")) {
            JOptionPane.showMessageDialog(this, "Veillez renseigner tous les champs!");
        } else {
            int ID_Admin = adao.getIdAdministrateur(Nom);
            int ID_Client = cdao.getIdClient(Prenom);
            Recevoir recu = new Recevoir(adao.getIdAdministrateur(Nom), cdao.getIdClient(Prenom));
            edao.inserer(recu);
            vider();
            liste_recu();
        }
    }//GEN-LAST:event_btn_enregistrerActionPerformed

    private void btn_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimerActionPerformed
        int index = tb_recu.getSelectedRow();

        if(index==-1) {
            JOptionPane.showMessageDialog(this, "Veillez selectionner une ligne!");
        } else {
            int id = (int) tb_recu.getValueAt(index, 0);
            RecevoirDAO edao = new RecevoirDAO();
            edao.supprimer(id);
            vider();
            liste_recu();
        }
    }//GEN-LAST:event_btn_supprimerActionPerformed

    private void btn_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifierActionPerformed
        RecevoirDAO edao = new RecevoirDAO();
        ClientDAO cdao = new ClientDAO();
        AdministrateurDAO adao = new AdministrateurDAO();

        //String ID_Admin = txt_admin.getSelectedItem().toString();
        String Nom = txt_admin.getSelectedItem().toString();
        
        //String ID_Client = txt_client.getSelectedItem().toString();
        String Prenom = txt_client.getSelectedItem().toString();

        if (Nom.equals("") || Prenom.equals("")) {
            JOptionPane.showMessageDialog(this, "Veillez renseigner tous les champs!");
        } else {
            int index = tb_recu.getSelectedRow();
            int id = (int) tb_recu.getValueAt(index, 0);
            Recevoir recu = new Recevoir(adao.getIdAdministrateur(Nom), cdao.getIdClient(Prenom));
            int ID_Admin = adao.getIdAdministrateur(Nom);
            int ID_Client = cdao.getIdClient(Prenom);
            edao.modifier(recu, id);
            vider();
            liste_recu();
        }
    }//GEN-LAST:event_btn_modifierActionPerformed

    private void tb_recuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_recuMouseClicked
        int index = tb_recu.getSelectedRow();

        if(index!=-1) {
            int id = (int) tb_recu.getValueAt(index, 0);
            RecevoirDAO edao = new RecevoirDAO();
            Recevoir recul = edao.rechercher(id);

            txt_admin.setSelectedItem(recul.getID_Admin());
            txt_client.setSelectedItem(recul.getID_Client());
        }
    }//GEN-LAST:event_tb_recuMouseClicked

    private void btn_imprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimerActionPerformed
        ReportRecevoir re = new ReportRecevoir();
        re.afficher_report();
    }//GEN-LAST:event_btn_imprimerActionPerformed

    private void txt_rechercherFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_rechercherFocusGained
        if(txt_rechercher.getText().equals("Entrez Votre Recherche...")){
            txt_rechercher.setText("");
            txt_rechercher.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_rechercherFocusGained

    private void txt_rechercherFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_rechercherFocusLost
        if(txt_rechercher.getText().equals("")){
            txt_rechercher.setText("Entrez Votre Recherche...");
            txt_rechercher.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_rechercherFocusLost

    private void txt_rechercherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rechercherKeyReleased
        DefaultTableModel model = (DefaultTableModel) tb_recu.getModel();
        TableRowSorter sorter = new TableRowSorter(model);
        tb_recu.setRowSorter(sorter);
        String rech = txt_rechercher.getText();
        sorter.setRowFilter(RowFilter.regexFilter(rech));
    }//GEN-LAST:event_txt_rechercherKeyReleased


    private void combo_admin() {
        AdministrateurDAO adao = new AdministrateurDAO();
        List<Administrateur> admin = adao.liste();
        txt_admin.addItem("");
        for(int i = 0; i < admin.size(); i++) {
            //txt_admin.addItem(admin.get(i).getID_Admin()+"");
            txt_admin.addItem(admin.get(i).getNom());
            adao.rechercher(admin.get(i).getID_Admin()).getNom();
       }
    }
    

    private void combo_client() {
        ClientDAO cdao = new ClientDAO();
        List<Client> client = cdao.liste();
        txt_client.addItem("");
        for(int i = 0; i < client.size(); i++) {
            //txt_client.addItem(client.get(i).getID_Client()+"");
            txt_client.addItem(client.get(i).getPrenom());
            cdao.rechercher(client.get(i).getID_Client()).getPrenom();
       }
    }
    
 
    private void liste_recu() {
        RecevoirDAO edao = new RecevoirDAO();
        ClientDAO cdao = new ClientDAO();
        AdministrateurDAO adao = new AdministrateurDAO();
        
        List<Recevoir> recevoir = edao.liste();
        
        for(int i = 0; i < recevoir.size(); i++) {
            ((DefaultTableModel) tb_recu.getModel()).addRow(new Object[] {
            recevoir.get(i).getId_recevoir(),
            
            //recevoir.get(i).getID_Admin(),
            adao.rechercher(recevoir.get(i).getID_Admin()).getNom(),
            
            //recevoir.get(i).getID_Client(),
            cdao.rechercher(recevoir.get(i).getID_Client()).getPrenom(),
            
        });
       }
    }

   public void vider() {
        txt_admin.setSelectedItem("");
        txt_client.setSelectedItem("");
        
        DefaultTableModel model = (DefaultTableModel) tb_recu.getModel();
        int n = model.getRowCount();
        for(int i = n - 1; i >= 0; --i) {
            model.removeRow(i);
        }
   }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_enregistrer;
    private javax.swing.JButton btn_imprimer;
    private javax.swing.JButton btn_modifier;
    private javax.swing.JButton btn_supprimer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loup;
    private javax.swing.JTable tb_recu;
    private javax.swing.JComboBox<String> txt_admin;
    private javax.swing.JComboBox<String> txt_client;
    private javax.swing.JTextField txt_rechercher;
    // End of variables declaration//GEN-END:variables
}
