/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import classes.Article;
import classes.Client;
import classes.Retirer;
import dao.ArticleDAO;
import dao.ClientDAO;
import dao.RetirerDAO;
import java.awt.Color;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import report.ReportRetrait;

/**
 *
 * @author kabor
 */
public class PanelRetrait extends javax.swing.JPanel {

    /**
     * Creates new form PanelRetrait
     */
    public PanelRetrait() {
        initComponents();
        combo_article();
        combo_client();
        liste_retirer();
        numram.setText(Integer.toString(nombreretraits()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_retrait = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_QtRetrait = new javax.swing.JFormattedTextField();
        txt_dateRetrait = new com.toedter.calendar.JDateChooser();
        btn_enregistrer = new javax.swing.JButton();
        btn_supprimer = new javax.swing.JButton();
        btn_modifier = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_client = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txt_article = new javax.swing.JComboBox<>();
        btn_imprimer = new javax.swing.JButton();
        txt_rechercher = new javax.swing.JTextField();
        loup = new javax.swing.JLabel();
        numram = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion De Ramassage", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Teko", 1, 36))); // NOI18N

        tb_retrait.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_retrait", "Date de Retrait", "Quantite de Retrait", "Libelle d'un article", "Prenom du client"
            }
        ));
        tb_retrait.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_retraitMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_retrait);

        jLabel1.setText("Date de retrait");

        jLabel2.setText("Quantite de retrait");

        btn_enregistrer.setFont(new java.awt.Font("Painting With Chocolate", 0, 11)); // NOI18N
        btn_enregistrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/btn/save_50px.png"))); // NOI18N
        btn_enregistrer.setText("Enregistrer");
        btn_enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enregistrerActionPerformed(evt);
            }
        });

        btn_supprimer.setFont(new java.awt.Font("Painting With Chocolate", 0, 11)); // NOI18N
        btn_supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/btn/Delete_48px.png"))); // NOI18N
        btn_supprimer.setText("Supprimer");
        btn_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimerActionPerformed(evt);
            }
        });

        btn_modifier.setFont(new java.awt.Font("Painting With Chocolate", 0, 11)); // NOI18N
        btn_modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/btn/icons8-modify-48.png"))); // NOI18N
        btn_modifier.setText("Modifier");
        btn_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifierActionPerformed(evt);
            }
        });

        jLabel3.setText("Client");

        jLabel4.setText("Article");

        btn_imprimer.setFont(new java.awt.Font("Painting With Chocolate", 0, 11)); // NOI18N
        btn_imprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/btn/icons8-print-48.png"))); // NOI18N
        btn_imprimer.setText("Imprimer");
        btn_imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimerActionPerformed(evt);
            }
        });

        txt_rechercher.setFont(new java.awt.Font("Rockwell Condensed", 0, 14)); // NOI18N
        txt_rechercher.setForeground(new java.awt.Color(153, 153, 153));
        txt_rechercher.setText("Entrez Votre Recherche...");
        txt_rechercher.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_rechercherFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_rechercherFocusLost(evt);
            }
        });
        txt_rechercher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_rechercherKeyReleased(evt);
            }
        });

        loup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Dashboard/searchloup1.gif"))); // NOI18N

        numram.setBackground(new java.awt.Color(255, 255, 255));
        numram.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_imprimer)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_article, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_client, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_QtRetrait)
                                    .addComponent(txt_dateRetrait, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_enregistrer)
                                .addGap(18, 18, 18)
                                .addComponent(btn_modifier)
                                .addGap(18, 18, 18)
                                .addComponent(btn_supprimer))
                            .addComponent(numram, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txt_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(loup)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_dateRetrait, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(txt_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_QtRetrait, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(loup))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_article, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(numram, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enregistrerActionPerformed
        RetirerDAO edao = new RetirerDAO();
        ArticleDAO adao = new ArticleDAO();
        ClientDAO cdao = new ClientDAO();

        Date Date_retrait = txt_dateRetrait.getDate();
        String Qt_retrait = txt_QtRetrait.getText();
        
        //String IDA = txt_article.getSelectedItem().toString();
        String LibelleA = txt_article.getSelectedItem().toString();
        
        //String ID_Client = txt_client.getSelectedItem().toString();
        String Prenom = txt_client.getSelectedItem().toString();

        if (Date_retrait == null || Qt_retrait.equals("") || LibelleA.equals("") || Prenom.equals("")) {
            JOptionPane.showMessageDialog(this, "Veillez renseigner tous les champs!");
        } else {
            int IDA = adao.getIdArticle(LibelleA);
            int ID_Client = cdao.getIdClient(Prenom);
            Retirer retire = new Retirer(Date_retrait, Integer.parseInt(Qt_retrait), adao.getIdArticle(LibelleA), cdao.getIdClient(Prenom));
            edao.inserer(retire);
            vider();
            liste_retirer();
        }
    }//GEN-LAST:event_btn_enregistrerActionPerformed

    private void btn_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimerActionPerformed
        int index = tb_retrait.getSelectedRow();

        if(index==-1) {
            JOptionPane.showMessageDialog(this, "Veillez selectionner une ligne!");
        } else {
            int id = (int) tb_retrait.getValueAt(index, 0);
            RetirerDAO edao = new RetirerDAO();
            edao.supprimer(id);
            vider();
            liste_retirer();
        }
    }//GEN-LAST:event_btn_supprimerActionPerformed

    private void btn_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifierActionPerformed
        RetirerDAO edao = new RetirerDAO();
        ArticleDAO adao = new ArticleDAO();
        ClientDAO cdao = new ClientDAO();
        
        Date Date_retrait = txt_dateRetrait.getDate();
        String Qt_retrait = txt_QtRetrait.getText();
        
        //String IDA = txt_article.getSelectedItem().toString();
        String LibelleA = txt_article.getSelectedItem().toString();
        
        //String ID_Client = txt_client.getSelectedItem().toString();
        String Prenom = txt_client.getSelectedItem().toString();

        if (Date_retrait == null || Qt_retrait.equals("") || LibelleA.equals("") || Prenom.equals("")) {
            JOptionPane.showMessageDialog(this, "Veillez renseigner tous les champs!");
        } else {
            int index = tb_retrait.getSelectedRow();
            int id = (int) tb_retrait.getValueAt(index, 0);
            Retirer retire = new Retirer(Date_retrait, Integer.parseInt(Qt_retrait), adao.getIdArticle(LibelleA), cdao.getIdClient(Prenom));
            int IDA = adao.getIdArticle(LibelleA);
            int ID_Client = cdao.getIdClient(Prenom);
            edao.modifier(retire, id);
            vider();
            liste_retirer();
        }
    }//GEN-LAST:event_btn_modifierActionPerformed

    private void tb_retraitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_retraitMouseClicked
        int index = tb_retrait.getSelectedRow();
        
        if(index!=-1) {
            int id = (int) tb_retrait.getValueAt(index, 0);
            RetirerDAO edao = new RetirerDAO();
            Retirer retirel = edao.rechercher(id);
            
            txt_dateRetrait.setDate(retirel.getDate_retrait());
            txt_QtRetrait.setText(retirel.getQt_retrait()+"");
            txt_article.setSelectedItem(retirel.getIDA()+"");
            txt_client.setSelectedItem(retirel.getID_Client()+"");
            
        } 
    }//GEN-LAST:event_tb_retraitMouseClicked

    private void btn_imprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimerActionPerformed
        ReportRetrait re = new ReportRetrait();
        re.afficher_report();
    }//GEN-LAST:event_btn_imprimerActionPerformed

    private void txt_rechercherFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_rechercherFocusGained
        if(txt_rechercher.getText().equals("Entrez Votre Recherche...")){
            txt_rechercher.setText("");
            txt_rechercher.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_rechercherFocusGained

    private void txt_rechercherFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_rechercherFocusLost
        if(txt_rechercher.getText().equals("")){
            txt_rechercher.setText("Entrez Votre Recherche...");
            txt_rechercher.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_rechercherFocusLost

    private void txt_rechercherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rechercherKeyReleased
        DefaultTableModel model = (DefaultTableModel) tb_retrait.getModel();
        TableRowSorter sorter = new TableRowSorter(model);
        tb_retrait.setRowSorter(sorter);
        String rech = txt_rechercher.getText();
        sorter.setRowFilter(RowFilter.regexFilter(rech));
    }//GEN-LAST:event_txt_rechercherKeyReleased

    private void combo_article() {
        ArticleDAO adao = new ArticleDAO();
        List<Article> article = adao.liste();
        txt_article.addItem("");
        for(int i = 0; i < article.size(); i++) {
            //txt_article.addItem(article.get(i).getIDA()+"");
            txt_article.addItem(article.get(i).getLibelleA());
            adao.rechercher(article.get(i).getIDA()).getLibelleA();
       }
    }

private void combo_client() {
        ClientDAO cdao = new ClientDAO();
        List<Client> client = cdao.liste();
        txt_client.addItem("");
        for(int i = 0; i < client.size(); i++) {
            //txt_client.addItem(client.get(i).getID_Client()+"");
            txt_client.addItem(client.get(i).getPrenom());
            cdao.rechercher(client.get(i).getID_Client()).getPrenom();
       }
    }
    
 
    private void liste_retirer() {
        RetirerDAO edao = new RetirerDAO();
        ArticleDAO adao = new ArticleDAO();
        ClientDAO cdao = new ClientDAO();
        
        List<Retirer> retirer = edao.liste();
        
        for(int i = 0; i < retirer.size(); i++) {
            ((DefaultTableModel) tb_retrait.getModel()).addRow(new Object[] {
            retirer.get(i).getId_retrait(),
            retirer.get(i).getDate_retrait(),
            retirer.get(i).getQt_retrait(),
            
            //retirer.get(i).getIDA(),
            adao.rechercher(retirer.get(i).getIDA()).getLibelleA(),
            
            //retirer.get(i).getID_Client(),
            cdao.rechercher(retirer.get(i).getID_Client()).getPrenom(),
                    
            
        });
       }
    }

   public void vider() {
       txt_dateRetrait.setDate(null); 
       txt_QtRetrait.setText("");
       txt_article.setSelectedItem("");
       txt_client.setSelectedItem("");
        
        DefaultTableModel model = (DefaultTableModel) tb_retrait.getModel();
        int n = model.getRowCount();
        for(int i = n - 1; i >= 0; --i) {
            model.removeRow(i);
        }
   }
   
   
   public int nombreretraits() {
        
        int rowsCount = tb_retrait.getRowCount();
        
        for(int i = 0; i < rowsCount; i++){
            int num = rowsCount;
        } 
        return rowsCount;
     }
   
   
   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_enregistrer;
    private javax.swing.JButton btn_imprimer;
    private javax.swing.JButton btn_modifier;
    private javax.swing.JButton btn_supprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loup;
    public static javax.swing.JLabel numram;
    private javax.swing.JTable tb_retrait;
    private javax.swing.JFormattedTextField txt_QtRetrait;
    private javax.swing.JComboBox<String> txt_article;
    private javax.swing.JComboBox<String> txt_client;
    private com.toedter.calendar.JDateChooser txt_dateRetrait;
    private javax.swing.JTextField txt_rechercher;
    // End of variables declaration//GEN-END:variables
}
