/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import classes.Article;
import classes.Client;
import classes.Deposer;
import dao.ArticleDAO;
import dao.ClientDAO;
import dao.DeposerDAO;
import java.awt.Color;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import report.ReportDepot;

/**
 *
 * @author kabor
 */
public class PanelDepot extends javax.swing.JPanel {

    /**
     * Creates new form PanelDepot
     */
    public PanelDepot() {
        initComponents();
        combo_article();
        combo_client();
        liste_deposer();
        numdep.setText(Integer.toString(nombredepots()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_QtDepot = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_depot = new javax.swing.JTable();
        btn_enregistrer = new javax.swing.JButton();
        btn_supprimer = new javax.swing.JButton();
        btn_modifier = new javax.swing.JButton();
        txt_dateDepot = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txt_client = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txt_article = new javax.swing.JComboBox<>();
        btn_imprimer = new javax.swing.JButton();
        txt_rechercher = new javax.swing.JTextField();
        loup = new javax.swing.JLabel();
        numdep = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion De Livraison", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Teko", 1, 36))); // NOI18N
        setMaximumSize(new java.awt.Dimension(32767, 511));
        setPreferredSize(new java.awt.Dimension(984, 511));

        jLabel1.setText("Date de depot");

        jLabel2.setText("Quantite de depot");

        tb_depot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_depot", "Date de Depot", "Quantite de Depot", "Libelle d'un article", "Prenom du client"
            }
        ));
        tb_depot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_depotMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_depot);

        btn_enregistrer.setFont(new java.awt.Font("Painting With Chocolate", 0, 11)); // NOI18N
        btn_enregistrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/btn/save_50px.png"))); // NOI18N
        btn_enregistrer.setText("Enregistrer");
        btn_enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enregistrerActionPerformed(evt);
            }
        });

        btn_supprimer.setFont(new java.awt.Font("Painting With Chocolate", 0, 11)); // NOI18N
        btn_supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/btn/Delete_48px.png"))); // NOI18N
        btn_supprimer.setText("Supprimer");
        btn_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimerActionPerformed(evt);
            }
        });

        btn_modifier.setFont(new java.awt.Font("Painting With Chocolate", 0, 11)); // NOI18N
        btn_modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/btn/icons8-modify-48.png"))); // NOI18N
        btn_modifier.setText("Modifier");
        btn_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifierActionPerformed(evt);
            }
        });

        jLabel3.setText("Client");

        jLabel4.setText("Article");

        btn_imprimer.setFont(new java.awt.Font("Painting With Chocolate", 0, 11)); // NOI18N
        btn_imprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/btn/icons8-print-48.png"))); // NOI18N
        btn_imprimer.setText("Imprimer");
        btn_imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimerActionPerformed(evt);
            }
        });

        txt_rechercher.setFont(new java.awt.Font("Rockwell Condensed", 0, 14)); // NOI18N
        txt_rechercher.setForeground(new java.awt.Color(153, 153, 153));
        txt_rechercher.setText("Entrez Votre Recherche...");
        txt_rechercher.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_rechercherFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_rechercherFocusLost(evt);
            }
        });
        txt_rechercher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_rechercherKeyReleased(evt);
            }
        });

        loup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Dashboard/searchloup1.gif"))); // NOI18N

        numdep.setBackground(new java.awt.Color(255, 255, 255));
        numdep.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_QtDepot)
                            .addComponent(txt_dateDepot, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)))
                    .addComponent(btn_imprimer)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(71, 71, 71)
                            .addComponent(txt_article, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_client, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btn_enregistrer)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_modifier)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_supprimer)))
                    .addComponent(numdep, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txt_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(loup)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_dateDepot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(txt_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_QtDepot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(loup))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_article, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txt_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(numdep, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enregistrerActionPerformed
        DeposerDAO edao = new DeposerDAO();
        ArticleDAO adao = new ArticleDAO();
        ClientDAO cdao = new ClientDAO();
        
        Date Date_depot = txt_dateDepot.getDate();
        String Qt_depot = txt_QtDepot.getText();
        
        //String IDA = txt_article.getSelectedItem().toString();
        String LibelleA = txt_article.getSelectedItem().toString();
        
        //String ID_Client = txt_client.getSelectedItem().toString();
        String Prenom = txt_client.getSelectedItem().toString();
        
        if (Date_depot == null || Qt_depot.equals("") || LibelleA.equals("") || Prenom.equals("")) {
            JOptionPane.showMessageDialog(this, "Veillez renseigner tous les champs!");
        } else {
            int IDA = adao.getIdArticle(LibelleA);
            int ID_Client = cdao.getIdClient(Prenom);
            Deposer depo = new Deposer(Date_depot, Integer.parseInt(Qt_depot), adao.getIdArticle(LibelleA), cdao.getIdClient(Prenom));
            edao.inserer(depo);
            vider();
            liste_deposer();
        }
    }//GEN-LAST:event_btn_enregistrerActionPerformed

    private void btn_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimerActionPerformed
        int index = tb_depot.getSelectedRow();

        if(index==-1) {
            JOptionPane.showMessageDialog(this, "Veillez selectionner une ligne!");
        } else {
            int id = (int) tb_depot.getValueAt(index, 0);
            DeposerDAO edao = new DeposerDAO();
            edao.supprimer(id);
            vider();
            liste_deposer();
        }
    }//GEN-LAST:event_btn_supprimerActionPerformed

    private void btn_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifierActionPerformed
        DeposerDAO edao = new DeposerDAO();
        ArticleDAO adao = new ArticleDAO();
        ClientDAO cdao = new ClientDAO();
        
        Date Date_depot = txt_dateDepot.getDate();
        String Qt_depot = txt_QtDepot.getText();
        //String IDA = txt_article.getSelectedItem().toString();
        String LibelleA = txt_article.getSelectedItem().toString();
        //String ID_Client = txt_client.getSelectedItem().toString();
        String Prenom = txt_client.getSelectedItem().toString();

        if (Date_depot == null || Qt_depot.equals("") || LibelleA.equals("") || Prenom.equals("")) {
            JOptionPane.showMessageDialog(this, "Veillez renseigner tous les champs!");
        } else {
            int index = tb_depot.getSelectedRow();
            int id = (int) tb_depot.getValueAt(index, 0);
            Deposer depo = new Deposer(Date_depot, Integer.parseInt(Qt_depot), adao.getIdArticle(LibelleA), cdao.getIdClient(Prenom));
            int IDA = adao.getIdArticle(LibelleA);
            int ID_Client = cdao.getIdClient(Prenom);
            edao.modifier(depo, id);
            vider();
            liste_deposer();
        }
    }//GEN-LAST:event_btn_modifierActionPerformed

    private void tb_depotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_depotMouseClicked
        int index = tb_depot.getSelectedRow();
        
        if(index!=-1) {
            int id = (int) tb_depot.getValueAt(index, 0);
            DeposerDAO edao = new DeposerDAO();
            Deposer depol = edao.rechercher(id);
            
            txt_dateDepot.setDate(depol.getDate_depot());
            txt_QtDepot.setText(depol.getQt_depot()+"");
            txt_article.setSelectedItem(depol.getIDA()+"");
            txt_client.setSelectedItem(depol.getID_Client()+"");
            
        } 
    }//GEN-LAST:event_tb_depotMouseClicked

    private void btn_imprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimerActionPerformed
        ReportDepot re = new ReportDepot();
        re.afficher_report();
    }//GEN-LAST:event_btn_imprimerActionPerformed

    private void txt_rechercherFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_rechercherFocusGained
        if(txt_rechercher.getText().equals("Entrez Votre Recherche...")){
            txt_rechercher.setText("");
            txt_rechercher.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_rechercherFocusGained

    private void txt_rechercherFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_rechercherFocusLost
        if(txt_rechercher.getText().equals("")){
            txt_rechercher.setText("Entrez Votre Recherche...");
            txt_rechercher.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_rechercherFocusLost

    private void txt_rechercherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rechercherKeyReleased
        DefaultTableModel model = (DefaultTableModel) tb_depot.getModel();
        TableRowSorter sorter = new TableRowSorter(model);
        tb_depot.setRowSorter(sorter);
        String rech = txt_rechercher.getText();
        sorter.setRowFilter(RowFilter.regexFilter(rech));
    }//GEN-LAST:event_txt_rechercherKeyReleased

private void combo_article() {
        ArticleDAO adao = new ArticleDAO();
        List<Article> article = adao.liste();
        txt_article.addItem("");
        for(int i = 0; i < article.size(); i++) {
            //txt_article.addItem(article.get(i).getIDA()+"");
            txt_article.addItem(article.get(i).getLibelleA());
            adao.rechercher(article.get(i).getIDA()).getLibelleA();
       }
    }

private void combo_client() {
        ClientDAO cdao = new ClientDAO();
        List<Client> client = cdao.liste();
        txt_client.addItem("");
        for(int i = 0; i < client.size(); i++) {
            //txt_client.addItem(client.get(i).getID_Client()+"");
            txt_client.addItem(client.get(i).getPrenom());
            cdao.rechercher(client.get(i).getID_Client()).getPrenom();
       }
    }
    
 
    private void liste_deposer() {
        DeposerDAO edao = new DeposerDAO();
        ArticleDAO adao = new ArticleDAO();
        ClientDAO cdao = new ClientDAO();
        
        List<Deposer> deposer = edao.liste();
        
        for(int i = 0; i < deposer.size(); i++) {
            ((DefaultTableModel) tb_depot.getModel()).addRow(new Object[] {
            deposer.get(i).getId_depot(),
            deposer.get(i).getDate_depot(),
            deposer.get(i).getQt_depot(),
            
            //deposer.get(i).getIDA(),
            adao.rechercher(deposer.get(i).getIDA()).getLibelleA(),
            
            //deposer.get(i).getID_Client(),
            cdao.rechercher(deposer.get(i).getID_Client()).getPrenom(),
            
        });
       }
    }

   public void vider() {
       txt_dateDepot.setDate(null); 
       txt_QtDepot.setText("");
       txt_article.setSelectedItem("");
       txt_client.setSelectedItem("");
        
        DefaultTableModel model = (DefaultTableModel) tb_depot.getModel();
        int n = model.getRowCount();
        for(int i = n - 1; i >= 0; --i) {
            model.removeRow(i);
        }
   }
   
   
   
   public int nombredepots() {
        
        int rowsCount = tb_depot.getRowCount();
        
        for(int i = 0; i < rowsCount; i++){
            int num = rowsCount;
        } 
        return rowsCount;
     }
   
   
   
   
   
   
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_enregistrer;
    private javax.swing.JButton btn_imprimer;
    private javax.swing.JButton btn_modifier;
    private javax.swing.JButton btn_supprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loup;
    public static javax.swing.JLabel numdep;
    private javax.swing.JTable tb_depot;
    private javax.swing.JFormattedTextField txt_QtDepot;
    private javax.swing.JComboBox<String> txt_article;
    private javax.swing.JComboBox<String> txt_client;
    private com.toedter.calendar.JDateChooser txt_dateDepot;
    private javax.swing.JTextField txt_rechercher;
    // End of variables declaration//GEN-END:variables
}
