/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import classes.Administrateur;
import dao.AdministrateurDAO;
import classes.Caisse;
import dao.CaisseDAO;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import report.ReportAdmin;

/**
 *
 * @author kabor
 */
public class PanelAdmin extends javax.swing.JPanel {

    /**
     * Creates new form PanelAdmin
     */
    public PanelAdmin() {
        initComponents();
        combo_caisse();
        liste_admin();
        numadmin.setText(Integer.toString(nombreadmin()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_nom = new javax.swing.JTextField();
        txt_prenom = new javax.swing.JTextField();
        txt_login = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        txt_profil = new javax.swing.JComboBox<>();
        btn_enregistrer = new javax.swing.JButton();
        btn_supprimer = new javax.swing.JButton();
        btn_modifier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_admin = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txt_caisse = new javax.swing.JComboBox<>();
        btn_imprimer = new javax.swing.JButton();
        numadmin = new javax.swing.JLabel();
        txt_rechercher = new javax.swing.JTextField();
        loup = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion Des Utilisateurs", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Teko", 1, 36))); // NOI18N
        setMaximumSize(new java.awt.Dimension(733, 440));
        setMinimumSize(new java.awt.Dimension(733, 440));
        setPreferredSize(new java.awt.Dimension(733, 440));

        jLabel1.setText("Nom");

        jLabel2.setText("Prenom");

        jLabel3.setText("Login");

        jLabel4.setText("Password");

        jLabel5.setText("Profil");

        txt_profil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrateur", "Utilisateur" }));

        btn_enregistrer.setFont(new java.awt.Font("Painting With Chocolate", 0, 11)); // NOI18N
        btn_enregistrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/btn/save_50px.png"))); // NOI18N
        btn_enregistrer.setText("Enregistrer");
        btn_enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enregistrerActionPerformed(evt);
            }
        });

        btn_supprimer.setFont(new java.awt.Font("Painting With Chocolate", 0, 11)); // NOI18N
        btn_supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/btn/Delete_48px.png"))); // NOI18N
        btn_supprimer.setText("Supprimer");
        btn_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimerActionPerformed(evt);
            }
        });

        btn_modifier.setFont(new java.awt.Font("Painting With Chocolate", 0, 11)); // NOI18N
        btn_modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/btn/icons8-modify-48.png"))); // NOI18N
        btn_modifier.setText("Modifier");
        btn_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifierActionPerformed(evt);
            }
        });

        tb_admin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Admin", "Nom", "Prenom", "Login", "Password", "Profil", "ID_Caisse"
            }
        ));
        tb_admin.setGridColor(new java.awt.Color(0, 153, 255));
        tb_admin.setShowGrid(false);
        tb_admin.setShowHorizontalLines(true);
        tb_admin.setShowVerticalLines(true);
        tb_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_adminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_admin);

        jLabel6.setText("Caisse");

        btn_imprimer.setFont(new java.awt.Font("Painting With Chocolate", 0, 11)); // NOI18N
        btn_imprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/btn/icons8-print-48.png"))); // NOI18N
        btn_imprimer.setText("Imprimer");
        btn_imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimerActionPerformed(evt);
            }
        });

        numadmin.setBackground(new java.awt.Color(255, 255, 255));
        numadmin.setForeground(new java.awt.Color(255, 255, 255));

        txt_rechercher.setFont(new java.awt.Font("Rockwell Condensed", 0, 14)); // NOI18N
        txt_rechercher.setForeground(new java.awt.Color(153, 153, 153));
        txt_rechercher.setText("Entrez Votre Recherche...");
        txt_rechercher.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_rechercherFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_rechercherFocusLost(evt);
            }
        });
        txt_rechercher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_rechercherKeyReleased(evt);
            }
        });

        loup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Dashboard/searchloup1.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_imprimer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_profil, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_caisse, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                                    .addComponent(txt_login, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_prenom, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nom, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(loup)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(404, 404, 404))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_enregistrer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_modifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_supprimer)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(loup)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txt_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_profil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_caisse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enregistrerActionPerformed
        AdministrateurDAO edao = new AdministrateurDAO();
        
        String Nom = txt_nom.getText();
        String Prenom = txt_prenom.getText();
        String Login_admin = txt_login.getText();
        //String Password_admin = txt_password.getText();
        String Password_admin = String.valueOf(txt_password.getPassword());
        String Profil_admin = txt_profil.getSelectedItem().toString();
        String ID_Caisse = txt_caisse.getSelectedItem().toString();
        
        if (Nom.equals("") || Prenom.equals("") || Login_admin.equals("") || Password_admin.equals("") || Profil_admin.equals("") || ID_Caisse.equals("")) {
            JOptionPane.showMessageDialog(this, "Veillez renseigner tous les champs!");
        } else {
            Administrateur ad = new Administrateur(Nom, Prenom, Login_admin, Password_admin, Profil_admin, Integer.parseInt(ID_Caisse));
            edao.inserer(ad);
            vider();
            liste_admin();
        }
    }//GEN-LAST:event_btn_enregistrerActionPerformed

    private void btn_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimerActionPerformed
        int index = tb_admin.getSelectedRow();
        
        if(index==-1) {
            JOptionPane.showMessageDialog(this, "Veillez selectionner une ligne!");
        } else {
            int id = (int) tb_admin.getValueAt(index, 0);
            AdministrateurDAO edao = new AdministrateurDAO();
            edao.supprimer(id);
            vider();
            liste_admin();
        }
    }//GEN-LAST:event_btn_supprimerActionPerformed

    private void btn_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifierActionPerformed
        AdministrateurDAO edao = new AdministrateurDAO();
        
        String Nom = txt_nom.getText();
        String Prenom = txt_prenom.getText();
        String Login_admin = txt_login.getText();
        //String Password_admin = txt_password.getText();
         String Password_admin = String.valueOf(txt_password.getPassword());
        String Profil_admin = txt_profil.getSelectedItem().toString();
        String ID_Caisse = txt_caisse.getSelectedItem().toString();
        
        if (Nom.equals("") || Prenom.equals("") || Login_admin.equals("") || Password_admin.equals("") || Profil_admin.equals("") || ID_Caisse.equals("")) {
            JOptionPane.showMessageDialog(this, "Veillez renseigner tous les champs!");
        } else {
            int index = tb_admin.getSelectedRow();
            int id = (int) tb_admin.getValueAt(index, 0);
            Administrateur ad = new Administrateur(Nom, Prenom, Login_admin, Password_admin, Profil_admin, Integer.parseInt(ID_Caisse));
            edao.modifier(ad, id);
            vider();
            liste_admin();
        }
    }//GEN-LAST:event_btn_modifierActionPerformed

    private void tb_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_adminMouseClicked
        int index = tb_admin.getSelectedRow();
        
        if(index!=-1) {
            int id = (int) tb_admin.getValueAt(index, 0);
            AdministrateurDAO edao = new AdministrateurDAO();
            Administrateur adl = edao.rechercher(id);
            
            txt_nom.setText(adl.getNom());
            txt_prenom.setText(adl.getPrenom());
            txt_login.setText(adl.getLogin_admin());
            txt_password.setText(adl.getPassword_admin());
            txt_profil.setSelectedItem(adl.getProfil_admin());
            txt_caisse.setSelectedItem(adl.getID_Caisse()+"");
        }
    }//GEN-LAST:event_tb_adminMouseClicked

    private void btn_imprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimerActionPerformed
        ReportAdmin re = new ReportAdmin();
        re.afficher_report();

    }//GEN-LAST:event_btn_imprimerActionPerformed

    private void txt_rechercherFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_rechercherFocusGained
        if(txt_rechercher.getText().equals("Entrez Votre Recherche...")){
            txt_rechercher.setText("");
            txt_rechercher.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_rechercherFocusGained

    private void txt_rechercherFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_rechercherFocusLost
        if(txt_rechercher.getText().equals("")){
            txt_rechercher.setText("Entrez Votre Recherche...");
            txt_rechercher.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_rechercherFocusLost

    private void txt_rechercherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rechercherKeyReleased
        DefaultTableModel model = (DefaultTableModel) tb_admin.getModel();
        TableRowSorter sorter = new TableRowSorter(model);
        tb_admin.setRowSorter(sorter);
        String rech = txt_rechercher.getText();
        sorter.setRowFilter(RowFilter.regexFilter(rech));
    }//GEN-LAST:event_txt_rechercherKeyReleased

    
    private void combo_caisse() {
        CaisseDAO edao = new CaisseDAO();
        List<Caisse> caisse = edao.liste();
        txt_caisse.addItem("");
        for(int i = 0; i < caisse.size(); i++) {
            txt_caisse.addItem(caisse.get(i).getID_Caisse()+"");
       }
    }
    
 
    private void liste_admin() {
        AdministrateurDAO edao = new AdministrateurDAO();
        List<Administrateur> administrateur = edao.liste();
        
        for(int i = 0; i < administrateur.size(); i++) {
            ((DefaultTableModel) tb_admin.getModel()).addRow(new Object[] {
            administrateur.get(i).getID_Admin(),
            administrateur.get(i).getNom(),
            administrateur.get(i).getPrenom(),
            administrateur.get(i).getLogin_admin(),
            administrateur.get(i).getPassword_admin(),
            administrateur.get(i).getProfil_admin(),
            administrateur.get(i).getID_Caisse()
            
        });
       }
    }

   public void vider() {
        txt_nom.setText("");
        txt_prenom.setText("");
        txt_login.setText("");
        txt_password.setText("");
        txt_profil.setSelectedItem("");
        txt_caisse.setSelectedItem("");
        
        DefaultTableModel model = (DefaultTableModel) tb_admin.getModel();
        int n = model.getRowCount();
        for(int i = n - 1; i >= 0; --i) {
            model.removeRow(i);
        }
    }
    
    public int nombreadmin() {
        
        int rowsCount = tb_admin.getRowCount();
        
        for(int i = 0; i < rowsCount; i++){
            int num = rowsCount;
        } 
        return rowsCount;
     }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_enregistrer;
    private javax.swing.JButton btn_imprimer;
    private javax.swing.JButton btn_modifier;
    private javax.swing.JButton btn_supprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loup;
    public static javax.swing.JLabel numadmin;
    private javax.swing.JTable tb_admin;
    private javax.swing.JComboBox<String> txt_caisse;
    private javax.swing.JTextField txt_login;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_prenom;
    private javax.swing.JComboBox<String> txt_profil;
    private javax.swing.JTextField txt_rechercher;
    // End of variables declaration//GEN-END:variables
}
