/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import classes.Article;
import dao.ArticleDAO;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import report.ReportArticle;

/**
 *
 * @author kabor
 */
public class PanelArticle extends javax.swing.JPanel {
    int count;
        int countSearch;
        int found;

    /**
     * Creates new form PanelArticle
     */
    public PanelArticle() {
        initComponents();
        liste_article();
        sumArt.setText(Integer.toString(calculArticle()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_prixua = new javax.swing.JFormattedTextField();
        btn_enregistrer = new javax.swing.JButton();
        btn_supprimer = new javax.swing.JButton();
        btn_modifier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_article = new javax.swing.JTable();
        btn_hommes = new javax.swing.JToggleButton();
        btn_femmes = new javax.swing.JToggleButton();
        btn_enfants = new javax.swing.JToggleButton();
        btn_bebes = new javax.swing.JToggleButton();
        btn_chambres = new javax.swing.JToggleButton();
        btn_salons = new javax.swing.JToggleButton();
        btn_cuisines = new javax.swing.JToggleButton();
        btn_saisons = new javax.swing.JToggleButton();
        txt_libellea = new javax.swing.JComboBox<>();
        sumArt = new javax.swing.JLabel();
        btn_imprimer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_rechercher = new javax.swing.JTextField();
        loup = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion Des Articles", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Teko", 1, 36))); // NOI18N

        jLabel1.setText("Libelle");

        jLabel2.setText("Prix Unitaire");

        btn_enregistrer.setFont(new java.awt.Font("Painting With Chocolate", 1, 11)); // NOI18N
        btn_enregistrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/btn/save_50px.png"))); // NOI18N
        btn_enregistrer.setText("Enregistrer");
        btn_enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enregistrerActionPerformed(evt);
            }
        });

        btn_supprimer.setFont(new java.awt.Font("Painting With Chocolate", 1, 11)); // NOI18N
        btn_supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/btn/Delete_48px.png"))); // NOI18N
        btn_supprimer.setText("Supprimer");
        btn_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimerActionPerformed(evt);
            }
        });

        btn_modifier.setFont(new java.awt.Font("Painting With Chocolate", 1, 11)); // NOI18N
        btn_modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/btn/icons8-modify-48.png"))); // NOI18N
        btn_modifier.setText("Modifier");
        btn_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifierActionPerformed(evt);
            }
        });

        tb_article.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDA", "Libelle Article", "Prix Unitaire Article"
            }
        ));
        tb_article.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_articleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_article);

        btn_hommes.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btn_hommes);
        btn_hommes.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        btn_hommes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/FrameArticle/icons8-costume-50.png"))); // NOI18N
        btn_hommes.setToolTipText("HOMMES");
        btn_hommes.setBorderPainted(false);
        btn_hommes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hommesActionPerformed(evt);
            }
        });

        btn_femmes.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btn_femmes);
        btn_femmes.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        btn_femmes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/FrameArticle/icons8-fashion-50.png"))); // NOI18N
        btn_femmes.setToolTipText("FEMMES");
        btn_femmes.setBorderPainted(false);
        btn_femmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_femmesActionPerformed(evt);
            }
        });

        btn_enfants.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btn_enfants);
        btn_enfants.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        btn_enfants.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/FrameArticle/icons8-clothes-50.png"))); // NOI18N
        btn_enfants.setToolTipText("ENFANTS");
        btn_enfants.setBorderPainted(false);
        btn_enfants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enfantsActionPerformed(evt);
            }
        });

        btn_bebes.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btn_bebes);
        btn_bebes.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        btn_bebes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/FrameArticle/icons8-romper-50.png"))); // NOI18N
        btn_bebes.setToolTipText("BEBES");
        btn_bebes.setBorderPainted(false);
        btn_bebes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bebesActionPerformed(evt);
            }
        });

        btn_chambres.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btn_chambres);
        btn_chambres.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        btn_chambres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/FrameArticle/icons8-bed-50.png"))); // NOI18N
        btn_chambres.setToolTipText("CHAMBRES");
        btn_chambres.setBorderPainted(false);
        btn_chambres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chambresActionPerformed(evt);
            }
        });

        btn_salons.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btn_salons);
        btn_salons.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        btn_salons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/FrameArticle/icons8-curtains-50.png"))); // NOI18N
        btn_salons.setToolTipText("SALONS");
        btn_salons.setBorderPainted(false);
        btn_salons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salonsActionPerformed(evt);
            }
        });

        btn_cuisines.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btn_cuisines);
        btn_cuisines.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        btn_cuisines.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/FrameArticle/icons8-apron-50.png"))); // NOI18N
        btn_cuisines.setToolTipText("CUISINES");
        btn_cuisines.setBorderPainted(false);
        btn_cuisines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cuisinesActionPerformed(evt);
            }
        });

        btn_saisons.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btn_saisons);
        btn_saisons.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        btn_saisons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/FrameArticle/icons8-mitten-50.png"))); // NOI18N
        btn_saisons.setToolTipText("SAISONS");
        btn_saisons.setBorderPainted(false);
        btn_saisons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saisonsActionPerformed(evt);
            }
        });

        sumArt.setForeground(new java.awt.Color(255, 255, 255));

        btn_imprimer.setFont(new java.awt.Font("Rockwell Condensed", 1, 11)); // NOI18N
        btn_imprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/btn/icons8-print-48.png"))); // NOI18N
        btn_imprimer.setText("Imprimer");
        btn_imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimerActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel3.setText("HOMMES");

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel4.setText("FEMMES");

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel5.setText("ENFANTS");

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel6.setText("BEBES");

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel7.setText("CHAMBRES");

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel8.setText("SALONS");

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel9.setText("CUISINES");

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel10.setText("SAISONS");

        txt_rechercher.setFont(new java.awt.Font("Rockwell Condensed", 0, 14)); // NOI18N
        txt_rechercher.setForeground(new java.awt.Color(153, 153, 153));
        txt_rechercher.setText("Entrez Votre Recherche...");
        txt_rechercher.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_rechercherFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_rechercherFocusLost(evt);
            }
        });
        txt_rechercher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_rechercherKeyReleased(evt);
            }
        });

        loup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Dashboard/searchloup1.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(txt_libellea, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(txt_prixua, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_enregistrer)
                                .addGap(11, 11, 11)
                                .addComponent(btn_supprimer)
                                .addGap(7, 7, 7)
                                .addComponent(btn_modifier))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_hommes, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_femmes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_enfants, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_bebes, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_chambres, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_salons)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_cuisines))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_saisons)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_imprimer)
                        .addGap(8, 8, 8)
                        .addComponent(sumArt, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txt_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(loup)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_hommes)
                            .addComponent(btn_femmes)
                            .addComponent(btn_enfants)
                            .addComponent(btn_bebes)
                            .addComponent(btn_chambres)
                            .addComponent(btn_salons)
                            .addComponent(btn_cuisines)
                            .addComponent(btn_saisons))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel7)))
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1))
                            .addComponent(txt_libellea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2))
                            .addComponent(txt_prixua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(143, 143, 143)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(130, 130, 130)
                                        .addComponent(sumArt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(btn_imprimer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loup)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(txt_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enregistrerActionPerformed
        ArticleDAO edao = new ArticleDAO();
        
        //String LibelleA = txt_libelleaa.getText();
        String LibelleA = txt_libellea.getSelectedItem().toString();
        String PrixUA = txt_prixua.getText();
        
        if (LibelleA.equals("") || PrixUA.equals("")) {
            JOptionPane.showMessageDialog(this, "Veillez renseigner tous les champs!");
        } else {
            Article ar = new Article(LibelleA, Integer.parseInt(PrixUA));
            edao.inserer(ar);
            vider();
            liste_article();
        }
    }//GEN-LAST:event_btn_enregistrerActionPerformed

    private void btn_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimerActionPerformed
        int index = tb_article.getSelectedRow();
        
        if(index==-1) {
            JOptionPane.showMessageDialog(this, "Veillez selectionner une ligne!");
        } else {
            int id = (int) tb_article.getValueAt(index, 0);
            ArticleDAO edao = new ArticleDAO();
            edao.supprimer(id);
            vider();
            liste_article();
        }
    }//GEN-LAST:event_btn_supprimerActionPerformed

    private void btn_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifierActionPerformed
         ArticleDAO edao = new ArticleDAO();
        
        //String LibelleA = txt_libelleaa.getText();
        String LibelleA = txt_libellea.getSelectedItem().toString();
        String PrixUA = txt_prixua.getText();
        
        if (LibelleA.equals("") || PrixUA.equals("")) {
            JOptionPane.showMessageDialog(this, "Veillez renseigner tous les champs!");
        } else {
            int index = tb_article.getSelectedRow();
            int id = (int) tb_article.getValueAt(index, 0);
            Article ar = new Article(LibelleA, Integer.parseInt(PrixUA));            
            edao.modifier(ar, id);
            vider();
            liste_article();
        }
    }//GEN-LAST:event_btn_modifierActionPerformed

    private void tb_articleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_articleMouseClicked
        int index = tb_article.getSelectedRow();
        
        if(index!=-1) {
            int id = (int) tb_article.getValueAt(index, 0);
            ArticleDAO edao = new ArticleDAO();
            Article arl = edao.rechercher(id);
            
            //txt_libelleaa.setText(arl.getLibelleA());
            txt_libellea.setSelectedItem(arl.getLibelleA());
            txt_prixua.setText(arl.getPrixUA()+"");
        }
    }//GEN-LAST:event_tb_articleMouseClicked

    private void btn_hommesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hommesActionPerformed
      
      if(btn_hommes.isSelected() == true) {
          btn_hommes.setBackground(Color.yellow);
          
          txt_libellea.removeAllItems();
          txt_libellea.addItem("Pantalon");
          txt_libellea.addItem("Veste");
          txt_libellea.addItem("Chemise");
          txt_libellea.addItem("Costume");
          txt_libellea.addItem("Nœud Papillon");
          txt_libellea.addItem("Cravate");
          txt_libellea.addItem("chemise polo");
          txt_libellea.addItem("Peignoir de Bain");
          txt_libellea.addItem("T-Shirt (Hommes)");
          
          btn_femmes.setBackground(Color.white);
          btn_enfants.setBackground(Color.white);
          btn_bebes.setBackground(Color.white);
          btn_chambres.setBackground(Color.white);
          btn_salons.setBackground(Color.white);
          btn_cuisines.setBackground(Color.white);
          btn_saisons.setBackground(Color.white);
        
        } else if (btn_hommes.isSelected() == false) {
            btn_hommes.setBackground(Color.white);
            txt_libellea.removeAllItems();
        }
        
        
        
    }//GEN-LAST:event_btn_hommesActionPerformed

    private void btn_femmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_femmesActionPerformed
        
        if(btn_femmes.isSelected() == true) {
          btn_femmes.setBackground(Color.yellow);
          
          btn_hommes.setBackground(Color.white);
          btn_enfants.setBackground(Color.white);
          btn_bebes.setBackground(Color.white);
          btn_chambres.setBackground(Color.white);
          btn_salons.setBackground(Color.white);
          btn_cuisines.setBackground(Color.white);
          btn_saisons.setBackground(Color.white);
           
          txt_libellea.removeAllItems();
          txt_libellea.addItem("Robe");
          txt_libellea.addItem("Jupe");
          txt_libellea.addItem("T-Shirt (Femmes)");
          txt_libellea.addItem("Robe de Mariée");
          txt_libellea.addItem("Robe Fourreau");
          txt_libellea.addItem("Vêtements de Gym");
          txt_libellea.addItem("Haut");
          
        } else if (btn_femmes.isSelected() == false) {
            btn_femmes.setBackground(Color.white);
            txt_libellea.removeAllItems();
        }
    }//GEN-LAST:event_btn_femmesActionPerformed

    private void btn_enfantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enfantsActionPerformed
        
        if(btn_enfants.isSelected() == true) {
          btn_enfants.setBackground(Color.yellow);
          
          btn_hommes.setBackground(Color.white);
          btn_femmes.setBackground(Color.white);
          btn_bebes.setBackground(Color.white);
          btn_chambres.setBackground(Color.white);
          btn_salons.setBackground(Color.white);
          btn_cuisines.setBackground(Color.white);
          btn_saisons.setBackground(Color.white);
           
          txt_libellea.removeAllItems();
          txt_libellea.addItem("Jeans");
          txt_libellea.addItem("Pantacourt");
          txt_libellea.addItem("Shirt");
          txt_libellea.addItem("Chemise enfants");
          txt_libellea.addItem("Short");
          txt_libellea.addItem("T-Shirt (enfants)");
          txt_libellea.addItem("Débardeur");
          txt_libellea.addItem("Salopette");
          
        } else if (btn_enfants.isSelected() == false) {
            btn_enfants.setBackground(Color.white);
             txt_libellea.removeAllItems();
        }
        
    }//GEN-LAST:event_btn_enfantsActionPerformed

    private void btn_bebesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bebesActionPerformed
        
        if(btn_bebes.isSelected() == true) {
          btn_bebes.setBackground(Color.yellow);
          
          btn_hommes.setBackground(Color.white);
          btn_femmes.setBackground(Color.white);
          btn_enfants.setBackground(Color.white);
          btn_chambres.setBackground(Color.white);
          btn_salons.setBackground(Color.white);
          btn_cuisines.setBackground(Color.white);
          btn_saisons.setBackground(Color.white);
           
          txt_libellea.removeAllItems();
          txt_libellea.addItem("Barboteuse");
          txt_libellea.addItem("Bavoir");
          txt_libellea.addItem("Grenouillère Bébé");
          txt_libellea.addItem("Veste en Denim");
          txt_libellea.addItem("Pyjama");
          txt_libellea.addItem("Tablier Bébé");
          txt_libellea.addItem("Salopette Bébé");
          txt_libellea.addItem("Mitaines");
          txt_libellea.addItem("Bonnet");
          txt_libellea.addItem("Maillot");
          txt_libellea.addItem("La Combinaison Bébé");
          txt_libellea.addItem("Bébé Body");
          
        } else if (btn_bebes.isSelected() == false) {
            btn_bebes.setBackground(Color.white);
             txt_libellea.removeAllItems();
        }
        
    }//GEN-LAST:event_btn_bebesActionPerformed

    private void btn_chambresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chambresActionPerformed
        
        if(btn_chambres.isSelected() == true) {
          btn_chambres.setBackground(Color.yellow);
          
          btn_hommes.setBackground(Color.white);
          btn_femmes.setBackground(Color.white);
          btn_enfants.setBackground(Color.white);
          btn_bebes.setBackground(Color.white);
          btn_salons.setBackground(Color.white);
          btn_cuisines.setBackground(Color.white);
          btn_saisons.setBackground(Color.white);
           
          txt_libellea.removeAllItems();
          txt_libellea.addItem("Garnitures D'oreillers pour Chambre");
          txt_libellea.addItem("Coussins de Chambre à Couché");
          txt_libellea.addItem("Taie D'oreiller pour Chambre");
          txt_libellea.addItem("Couette");
          txt_libellea.addItem("Housse de Couette");
          txt_libellea.addItem("Couverture");
          txt_libellea.addItem("Drap");
          txt_libellea.addItem("Tapis de Chambre à Couché");
          txt_libellea.addItem("Rideaux Transparents");
          
        } else if (btn_chambres.isSelected() == false) {
            btn_chambres.setBackground(Color.white);
            txt_libellea.removeAllItems();
        }
        
    }//GEN-LAST:event_btn_chambresActionPerformed

    private void btn_salonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salonsActionPerformed
        
        if(btn_salons.isSelected() == true) {
          btn_salons.setBackground(Color.yellow);
          
          btn_hommes.setBackground(Color.white);
          btn_femmes.setBackground(Color.white);
          btn_enfants.setBackground(Color.white);
          btn_bebes.setBackground(Color.white);
          btn_chambres.setBackground(Color.white);
          btn_cuisines.setBackground(Color.white);
          btn_saisons.setBackground(Color.white);
           
          txt_libellea.removeAllItems();
          txt_libellea.addItem("Garnitures D'oreillers pour Salon");
          txt_libellea.addItem("Coussins de Salon");
          txt_libellea.addItem("Taie D'oreiller pour Salon");
          txt_libellea.addItem("Rideaux de Salon");
          txt_libellea.addItem("Housse de Canapé");
          txt_libellea.addItem("Tapis de Salon");
          
        } else if (btn_salons.isSelected() == false) {
            btn_salons.setBackground(Color.white);
            txt_libellea.removeAllItems();
        }
        
    }//GEN-LAST:event_btn_salonsActionPerformed

    private void btn_cuisinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cuisinesActionPerformed
        
        if(btn_cuisines.isSelected() == true) {
          btn_cuisines.setBackground(Color.yellow);
          
          btn_hommes.setBackground(Color.white);
          btn_femmes.setBackground(Color.white);
          btn_enfants.setBackground(Color.white);
          btn_bebes.setBackground(Color.white);
          btn_chambres.setBackground(Color.white);
          btn_salons.setBackground(Color.white);
          btn_saisons.setBackground(Color.white);
           
          txt_libellea.removeAllItems();
          txt_libellea.addItem("Tablier");
          txt_libellea.addItem("Serviette de Table");
          txt_libellea.addItem("Taie D'oreiller pour Salon");
          txt_libellea.addItem("Nappe");
          txt_libellea.addItem("Tapis de Cuisine");
          txt_libellea.addItem("Gants de Four");
          txt_libellea.addItem("Torchon");
          
        } else if (btn_cuisines.isSelected() == false) {
            btn_cuisines.setBackground(Color.white);
            txt_libellea.removeAllItems();
        }
        
    }//GEN-LAST:event_btn_cuisinesActionPerformed

    private void btn_saisonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saisonsActionPerformed
        
        if(btn_saisons.isSelected() == true) {
          btn_saisons.setBackground(Color.yellow);
          
          btn_hommes.setBackground(Color.white);
          btn_femmes.setBackground(Color.white);
          btn_enfants.setBackground(Color.white);
          btn_bebes.setBackground(Color.white);
          btn_chambres.setBackground(Color.white);
          btn_salons.setBackground(Color.white);
          btn_cuisines.setBackground(Color.white);
           
          txt_libellea.removeAllItems();
          txt_libellea.addItem("Bonnet");
          txt_libellea.addItem("Chandail");
          txt_libellea.addItem("Veste Polaire");
          txt_libellea.addItem("Mitaines");
          txt_libellea.addItem("Foulard");
          txt_libellea.addItem("Bottes");
          txt_libellea.addItem("Manteaux");
          txt_libellea.addItem("Cache-oreilles");
          txt_libellea.addItem("Cardigan");
          txt_libellea.addItem("Maillot de Bain");
          txt_libellea.addItem("Chaussettes de Sport");
          
        } else if (btn_saisons.isSelected() == false) {
            btn_saisons.setBackground(Color.white);
            txt_libellea.removeAllItems();
        }
        
    }//GEN-LAST:event_btn_saisonsActionPerformed

    private void btn_imprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimerActionPerformed
        ReportArticle re = new ReportArticle();
        re.afficher_report();
    }//GEN-LAST:event_btn_imprimerActionPerformed

    private void txt_rechercherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rechercherKeyReleased
        DefaultTableModel model = (DefaultTableModel) tb_article.getModel();
        TableRowSorter sorter = new TableRowSorter(model);
        tb_article.setRowSorter(sorter);
        String rech = txt_rechercher.getText();
        sorter.setRowFilter(RowFilter.regexFilter(rech));
        
    }//GEN-LAST:event_txt_rechercherKeyReleased

    private void txt_rechercherFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_rechercherFocusGained
        if(txt_rechercher.getText().equals("Entrez Votre Recherche...")){
            txt_rechercher.setText("");
            txt_rechercher.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_rechercherFocusGained

    private void txt_rechercherFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_rechercherFocusLost
        if(txt_rechercher.getText().equals("")){
            txt_rechercher.setText("Entrez Votre Recherche...");
            txt_rechercher.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_rechercherFocusLost
   
    

    

    private void liste_article() {
        ArticleDAO edao = new ArticleDAO();
        List<Article> article = edao.liste();
        
        for(int i = 0; i < article.size(); i++) {
            ((DefaultTableModel) tb_article.getModel()).addRow(new Object[] {
            article.get(i).getIDA(),
            article.get(i).getLibelleA(),
            article.get(i).getPrixUA(),
        });
       }
    }

   public void vider() {
        //txt_libelleaa.setText("");
        txt_libellea.setSelectedItem(""); 
        txt_prixua.setText("");
        
        DefaultTableModel model = (DefaultTableModel) tb_article.getModel();
        int n = model.getRowCount();
        for(int i = n - 1; i >= 0; --i) {
            model.removeRow(i);
        }
    }
    
   public int calculArticle() {
     
        int rowsCount = tb_article.getRowCount();
        
        int total = 0; 
        for(int i = 0; i < rowsCount; i++){
            total = total+Integer.parseInt(tb_article.getValueAt(i, 2).toString());
        } 
        return total;
        //sum.setText(Integer.toString(calculer()));
     }
   
   
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_bebes;
    private javax.swing.JToggleButton btn_chambres;
    private javax.swing.JToggleButton btn_cuisines;
    private javax.swing.JToggleButton btn_enfants;
    private javax.swing.JButton btn_enregistrer;
    private javax.swing.JToggleButton btn_femmes;
    private javax.swing.JToggleButton btn_hommes;
    private javax.swing.JButton btn_imprimer;
    private javax.swing.JButton btn_modifier;
    private javax.swing.JToggleButton btn_saisons;
    private javax.swing.JToggleButton btn_salons;
    private javax.swing.JButton btn_supprimer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loup;
    public static javax.swing.JLabel sumArt;
    public javax.swing.JTable tb_article;
    private javax.swing.JComboBox<String> txt_libellea;
    private javax.swing.JFormattedTextField txt_prixua;
    private javax.swing.JTextField txt_rechercher;
    // End of variables declaration//GEN-END:variables
}
